<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.3">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Tree-Based Methods – Statistical Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../contents/3/ensemble.html" rel="next">
<link href="../../contents/2/lda.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bc74d3edfa28a5cab5f8e807a64bb1a0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-c0ebe27be8de1e3ea6af4b63718550d7.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bc74d3edfa28a5cab5f8e807a64bb1a0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-34c91892f896ce4854c4dcc1026a7fe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-7e342b42b1d8244df6d5a8d63372ab02.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-34c91892f896ce4854c4dcc1026a7fe2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles/fonts.css">
<link rel="stylesheet" href="../../styles/blocks.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tree-Based Methods</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Statistical Learning</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Linear models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/1/lr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/1/shrinkage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/1/dr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Dimension reduction</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Classification</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/2/logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/2/lda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">LDA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Tree Based Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/3/tree.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tree-Based Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/3/ensemble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ensemble Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Distance Based Methods</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/4/knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">KNN Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/4/kernel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">kernel.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contents/4/cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">cluster.html</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#cart-classification-and-regression-trees" id="toc-cart-classification-and-regression-trees" class="nav-link active" data-scroll-target="#cart-classification-and-regression-trees"><span class="header-section-number">6.1</span> CART: Classification and Regression Trees</a>
  <ul class="collapse">
  <li><a href="#splitting-a-dataset" id="toc-splitting-a-dataset" class="nav-link" data-scroll-target="#splitting-a-dataset"><span class="header-section-number">6.1.1</span> Splitting a Dataset</a></li>
  </ul></li>
  <li><a href="#classification-trees" id="toc-classification-trees" class="nav-link" data-scroll-target="#classification-trees"><span class="header-section-number">6.2</span> Classification Trees</a>
  <ul class="collapse">
  <li><a href="#gini-impurity" id="toc-gini-impurity" class="nav-link" data-scroll-target="#gini-impurity"><span class="header-section-number">6.2.1</span> Gini Impurity</a></li>
  </ul></li>
  <li><a href="#regression-trees" id="toc-regression-trees" class="nav-link" data-scroll-target="#regression-trees"><span class="header-section-number">6.3</span> Regression Trees</a>
  <ul class="collapse">
  <li><a href="#split-criterion-for-regression-trees" id="toc-split-criterion-for-regression-trees" class="nav-link" data-scroll-target="#split-criterion-for-regression-trees"><span class="header-section-number">6.3.1</span> Split Criterion for Regression Trees</a></li>
  <li><a href="#interpretation-of-regression-trees" id="toc-interpretation-of-regression-trees" class="nav-link" data-scroll-target="#interpretation-of-regression-trees"><span class="header-section-number">6.3.2</span> Interpretation of Regression Trees</a></li>
  </ul></li>
  <li><a href="#pros-and-cons" id="toc-pros-and-cons" class="nav-link" data-scroll-target="#pros-and-cons"><span class="header-section-number">6.4</span> Pros and cons</a></li>
  <li><a href="#tuning-hyperparameters" id="toc-tuning-hyperparameters" class="nav-link" data-scroll-target="#tuning-hyperparameters"><span class="header-section-number">6.5</span> Tuning hyperparameters</a></li>
  <li><a href="#pruning" id="toc-pruning" class="nav-link" data-scroll-target="#pruning"><span class="header-section-number">6.6</span> Pruning</a></li>
  <li><a href="#trees-in-python" id="toc-trees-in-python" class="nav-link" data-scroll-target="#trees-in-python"><span class="header-section-number">6.7</span> Trees in Python</a></li>
  <li><a href="#tree" id="toc-tree" class="nav-link" data-scroll-target="#tree"><span class="header-section-number">7</span> Tree</a>
  <ul class="collapse">
  <li><a href="#classification-tree" id="toc-classification-tree" class="nav-link" data-scroll-target="#classification-tree"><span class="header-section-number">7.1</span> Classification Tree</a>
  <ul class="collapse">
  <li><a href="#gini-impurity-2" id="toc-gini-impurity-2" class="nav-link" data-scroll-target="#gini-impurity-2"><span class="header-section-number">7.1.1</span> Gini impurity</a></li>
  </ul></li>
  <li><a href="#a-single-split" id="toc-a-single-split" class="nav-link" data-scroll-target="#a-single-split"><span class="header-section-number">7.2</span> 3. A single split</a></li>
  <li><a href="#recursive-binary-splitting" id="toc-recursive-binary-splitting" class="nav-link" data-scroll-target="#recursive-binary-splitting"><span class="header-section-number">7.3</span> 4. Recursive binary splitting</a></li>
  <li><a href="#candidate-cutoffs" id="toc-candidate-cutoffs" class="nav-link" data-scroll-target="#candidate-cutoffs"><span class="header-section-number">7.4</span> 5. Candidate cutoffs</a></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">7.5</span> 6. Prediction</a></li>
  <li><a href="#adaptive-kernel-view" id="toc-adaptive-kernel-view" class="nav-link" data-scroll-target="#adaptive-kernel-view"><span class="header-section-number">7.6</span> 7. Adaptive kernel view</a></li>
  <li><a href="#geometry" id="toc-geometry" class="nav-link" data-scroll-target="#geometry"><span class="header-section-number">7.7</span> 8. Geometry</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions"><span class="header-section-number">7.8</span> 9. Interactions</a></li>
  <li><a href="#cart-algorithms" id="toc-cart-algorithms" class="nav-link" data-scroll-target="#cart-algorithms"><span class="header-section-number">7.9</span> CART Algorithms</a>
  <ul class="collapse">
  <li><a href="#ideas" id="toc-ideas" class="nav-link" data-scroll-target="#ideas"><span class="header-section-number">7.9.1</span> Ideas</a></li>
  </ul></li>
  <li><a href="#decision-tree-project-1-the-iris-dataset" id="toc-decision-tree-project-1-the-iris-dataset" class="nav-link" data-scroll-target="#decision-tree-project-1-the-iris-dataset"><span class="header-section-number">7.10</span> Decision Tree Project 1: the <code>iris</code> dataset</a>
  <ul class="collapse">
  <li><a href="#initial-setup" id="toc-initial-setup" class="nav-link" data-scroll-target="#initial-setup"><span class="header-section-number">7.10.1</span> Initial setup</a></li>
  <li><a href="#use-package-sklearn" id="toc-use-package-sklearn" class="nav-link" data-scroll-target="#use-package-sklearn"><span class="header-section-number">7.10.2</span> Use package <code>sklearn</code></a></li>
  <li><a href="#tuning-hyperparameters-1" id="toc-tuning-hyperparameters-1" class="nav-link" data-scroll-target="#tuning-hyperparameters-1"><span class="header-section-number">7.10.3</span> Tuning hyperparameters</a></li>
  <li><a href="#pruning-1" id="toc-pruning-1" class="nav-link" data-scroll-target="#pruning-1"><span class="header-section-number">7.10.4</span> Pruning</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#regression-trees-1" id="toc-regression-trees-1" class="nav-link" data-scroll-target="#regression-trees-1"><span class="header-section-number">8</span> Regression Trees</a>
  <ul class="collapse">
  <li><a href="#why-trees" id="toc-why-trees" class="nav-link" data-scroll-target="#why-trees"><span class="header-section-number">8.1</span> 1. Why trees?</a></li>
  <li><a href="#tree-complexity" id="toc-tree-complexity" class="nav-link" data-scroll-target="#tree-complexity"><span class="header-section-number">8.2</span> 10. Tree complexity</a></li>
  <li><a href="#stopping-rules" id="toc-stopping-rules" class="nav-link" data-scroll-target="#stopping-rules"><span class="header-section-number">8.3</span> 11. Stopping rules</a></li>
  <li><a href="#cost-complexity-pruning" id="toc-cost-complexity-pruning" class="nav-link" data-scroll-target="#cost-complexity-pruning"><span class="header-section-number">8.4</span> 12. Cost-complexity pruning</a></li>
  <li><a href="#bias-variance-tradeoff" id="toc-bias-variance-tradeoff" class="nav-link" data-scroll-target="#bias-variance-tradeoff"><span class="header-section-number">8.5</span> 13. Bias-variance tradeoff</a></li>
  <li><a href="#variable-importance" id="toc-variable-importance" class="nav-link" data-scroll-target="#variable-importance"><span class="header-section-number">8.6</span> 14. Variable importance</a></li>
  <li><a href="#strengths" id="toc-strengths" class="nav-link" data-scroll-target="#strengths"><span class="header-section-number">8.7</span> 15. Strengths</a></li>
  <li><a href="#weaknesses" id="toc-weaknesses" class="nav-link" data-scroll-target="#weaknesses"><span class="header-section-number">8.8</span> 16. Weaknesses</a></li>
  <li><a href="#minimal-python-example" id="toc-minimal-python-example" class="nav-link" data-scroll-target="#minimal-python-example"><span class="header-section-number">8.9</span> 17. Minimal Python example</a></li>
  <li><a href="#cost-complexity-pruning-path-in-sklearn" id="toc-cost-complexity-pruning-path-in-sklearn" class="nav-link" data-scroll-target="#cost-complexity-pruning-path-in-sklearn"><span class="header-section-number">8.10</span> 18. Cost-complexity pruning path in sklearn</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.11</span> 19. Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tree-Based Methods</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A decision tree is a nonparametric method. Instead of assuming a global linear relationship such as <span class="math inline">\(f(x)=\beta_0+\beta_1x_1+\cdots+\beta_px_p\)</span>, a tree learns a collection of simple if-then rules directly from the data.</p>
<p>The basic idea is:</p>
<ol type="1">
<li>Split the feature space into regions.</li>
<li>Continue splitting each region into smaller regions.</li>
<li>Use the observations inside each final region to make predictions.</li>
</ol>
<!-- A decision tree is called **adaptive** because the regions are learned from the data.

* If a predictor is useful, the tree may split on it many times.
* If a predictor is not useful, the tree may ignore it completely. -->
<!-- 
Unlike linear regression, trees can naturally model nonlinear relationships and complicated interactions between predictors.

--- -->
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.1 (Example: A Classification Tree)</strong></span> &nbsp;</p>
<div id="0ab04901" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-2-output-1.png" width="505" height="502" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is a classification tree. The tree repeatedly asks simple questions such as</p>
<ul>
<li>Is <code>x[1] &lt;= 0.8</code>?</li>
<li>Is <code>x[1] &lt;= 1.75</code>?</li>
</ul>
<p>Each split divides the feature space into smaller regions.</p>
<p>Notice that a tree may split on the same predictor multiple times. This is very common in practice. This suggests that the feature <code>x[1]</code> is more important than other features.</p>
</div>
<!-- 
# Why Trees Are Nonlinear

A tree partitions the feature space into regions and predicts separately inside each region.

For example:

* If age < 30, predict salary = $45,000
* Otherwise predict salary = $82,000

This creates a **piecewise prediction rule** instead of one global linear equation.

Therefore trees are naturally nonlinear models.

--- -->
<section id="cart-classification-and-regression-trees" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="cart-classification-and-regression-trees"><span class="header-section-number">6.1</span> CART: Classification and Regression Trees</h2>
<p>There are many algorithms for constructing decision trees. The most common one is called CART (Classification and Regression Trees).</p>
<p>CART has the following properties:</p>
<ul>
<li>It creates only binary splits;</li>
<li>For classification, common splitting criteria include Gini impurity and Entropy;</li>
<li>For regression, common splitting criteria include Mean squared error (MSE) and Sum of squared errors (SSE).</li>
</ul>
<section id="splitting-a-dataset" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="splitting-a-dataset"><span class="header-section-number">6.1.1</span> Splitting a Dataset</h3>
<p>At each step, CART searches for the best split.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm: Split the Dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Inputs:</strong> A dataset</p>
<p><span class="math display">\[
S={[\text{features},\text{target}]}
\]</span></p>
<p><strong>Outputs:</strong> The best split <span class="math inline">\((k,t)\)</span></p>
<ol type="1">
<li><p>For each feature <span class="math inline">\(k\)</span>:</p>
<ol type="1">
<li><p>For each candidate split value <span class="math inline">\(t\)</span>:</p>
<ol type="1">
<li>Split the dataset into two subsets:</li>
</ol>
<p><span class="math display">\[
G_l={x_k\le t},
\qquad
G_r={x_k&gt;t}
\]</span></p>
<ol start="2" type="1">
<li>Compute the split cost function <span class="math inline">\(J(k,t)\)</span></li>
<li>Compare with the current best split</li>
</ol></li>
</ol></li>
<li><p>Return the split <span class="math inline">\((k,t)\)</span> with the smallest cost</p></li>
</ol>
</div>
</div>
<p>The splitting algorithm is applied recursively.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm: CART
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Inputs:</strong></p>
<ul>
<li>A labeled dataset <span class="math inline">\(S\)</span></li>
<li>A maximal tree depth <code>max_depth</code></li>
</ul>
<p><strong>Outputs:</strong></p>
<ul>
<li>A decision tree</li>
</ul>
<ol type="1">
<li><p>Start with the original dataset <span class="math inline">\(S\)</span></p></li>
<li><p>If the node is not pure:</p>
<ol type="1">
<li>Find the best split</li>
<li>Split the node into:</li>
</ol>
<p><span class="math display">\[
G_l,
\qquad
G_r
\]</span></p></li>
<li><p>Apply the same procedure recursively to both child nodes</p></li>
<li><p>Stop when:</p>
<ul>
<li>the maximal depth is reached, or</li>
<li>the node becomes pure, or</li>
<li>further splitting is impossible</li>
</ul></li>
</ol>
</div>
</div>
</section>
</section>
<section id="classification-trees" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="classification-trees"><span class="header-section-number">6.2</span> Classification Trees</h2>
<p>For classification trees, we need a criterion to measure whether a split is good or bad. The two most common choices are:</p>
<ul>
<li>Gini impurity</li>
<li>Entropy</li>
</ul>
<p>Their performance is usually very similar. In these notes we focus on Gini impurity because it is slightly easier to compute and interpret.</p>
<section id="gini-impurity" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="gini-impurity"><span class="header-section-number">6.2.1</span> Gini Impurity</h3>
<p>Assume that a node contains <span class="math inline">\(n\)</span> observations divided into <span class="math inline">\(K\)</span> classes.</p>
<p>Let</p>
<p><span class="math display">\[
p_i=\frac{n_i}{n}
\]</span></p>
<p>be the proportion of class <span class="math inline">\(i\)</span>.</p>
<p>If we randomly assign labels according to the class proportions, then:</p>
<ul>
<li>the probability an observation belongs to class <span class="math inline">\(i\)</span> is <span class="math inline">\(p_i\)</span></li>
<li>the probability we incorrectly classify it is <span class="math inline">\(1-p_i\)</span></li>
</ul>
<p>Therefore the probability of misclassifying an observation from class <span class="math inline">\(i\)</span> is</p>
<p><span class="math display">\[
p_i(1-p_i).
\]</span></p>
<p>Summing over all classes gives</p>
<p><span class="math display">\[
\sum_{i=1}^K p_i(1-p_i).
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
\sum_{i=1}^K p_i=1,
\]</span></p>
<p>we obtain</p>
<p><span class="math display">\[
Gini
=\sum_{i=1}^K p_i(1-p_i)
=1-\sum_{i=1}^K p_i^2.
\]</span></p>
<div id="def-gini" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.1 (Gini Impurity)</strong></span> The <strong>Gini impurity</strong> of a node is</p>
<p><span class="math display">\[
Gini
=1-\sum_{i=1}^K p_i^2,
\]</span></p>
<p>where <span class="math inline">\(p_i\)</span> is the proportion of class <span class="math inline">\(i\)</span> inside the node.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.2 (Pure node)</strong></span> Suppose a node contains observations from only one class.</p>
<p>Then one of the probabilities equals 1 and all others equal 0.</p>
<p>Therefore</p>
<p><span class="math display">\[
Gini=1-1^2=0.
\]</span></p>
<p>This is the minimum possible impurity.</p>
<p>A node with Gini impurity 0 is called a pure node.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.3 (Two-Class Example)</strong></span> Suppose we have two classes.</p>
<p>Let</p>
<p><span class="math display">\[
p_2=1-p_1.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
Gini
=1-p_1^2-(1-p_1)^2
=2p_1-2p_1^2.
\]</span></p>
<p>When:</p>
<ul>
<li><span class="math inline">\(p_1=0\)</span> or <span class="math inline">\(1\)</span>, the impurity is 0</li>
<li><span class="math inline">\(p_1=0.5\)</span>, the impurity is maximized</li>
</ul>
<p>Therefore impurity is largest when the classes are balanced.</p>
</div>
<p>The impurity of a node itself is not enough. CART actually evaluates the quality of a split by examining the impurity of the child nodes after splitting.</p>
<p>Suppose a node <span class="math inline">\(G\)</span> is split into:</p>
<p><span class="math display">\[
G_l,
\qquad
G_r.
\]</span></p>
<p>The split cost is</p>
<p><span class="math display">\[
J
=\frac{|G_l|}{|G|}Gini(G_l)
+\frac{|G_r|}{|G|}Gini(G_r).
\]</span></p>
<p>A good split produces child nodes with low impurity.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entropy
</div>
</div>
<div class="callout-body-container callout-body">
<p>Entropy is another popular impurity measure.</p>
<p>Its formula is</p>
<p><span class="math display">\[
Entropy
=-\sum_{i=1}^K p_i\log(p_i).
\]</span></p>
<p>Entropy and Gini impurity usually produce very similar trees.</p>
<p>Because Gini impurity is slightly simpler computationally and conceptually, we mainly focus on it.</p>
</div>
</div>
</section>
</section>
<section id="regression-trees" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="regression-trees"><span class="header-section-number">6.3</span> Regression Trees</h2>
<p>Regression trees are used when the response variable is quantitative. Instead of predicting a class label, a regression tree predicts a numerical value.</p>
<p>Suppose a terminal node contains responses</p>
<p><span class="math display">\[
y_1,y_2,\ldots,y_n.
\]</span></p>
<p>The prediction for that region is usually the sample mean:</p>
<p><span class="math display">\[
\hat y
=\frac{1}{n}\sum_{i=1}^n y_i.
\]</span></p>
<p>Therefore regression trees approximate the regression function using piecewise constant regions.</p>
<section id="split-criterion-for-regression-trees" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="split-criterion-for-regression-trees"><span class="header-section-number">6.3.1</span> Split Criterion for Regression Trees</h3>
<p>For regression trees, CART typically minimizes the residual sum of squares (RSS) or equivalently the mean squared error (MSE).</p>
<p>Suppose a split divides the data into two regions:</p>
<p><span class="math display">\[
G_l,
\qquad
G_r.
\]</span></p>
<p>The split cost is</p>
<p>$$ RSS ===</p>
<p><em>{iG_l}(y_i-y_l)^2 + </em>{iG_r}(y_i-y_r)^2, $$</p>
<p>where</p>
<p><span class="math display">\[
\bar y_l
\qquad\text{and}\qquad
\bar y_r
\]</span></p>
<p>are the mean responses inside the two regions.</p>
<p>The best split is the one that minimizes this quantity.</p>
</section>
<section id="interpretation-of-regression-trees" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="interpretation-of-regression-trees"><span class="header-section-number">6.3.2</span> Interpretation of Regression Trees</h3>
<p>A regression tree creates regions with similar response values.</p>
<p>For example:</p>
<ul>
<li>If age &lt; 30, predict salary = $45,000</li>
<li>If age ≥ 30 and education &lt; 16 years, predict salary = $68,000</li>
<li>Otherwise predict salary = $95,000</li>
</ul>
<p>Thus a regression tree approximates a complicated nonlinear function using many simple local averages.</p>
</section>
</section>
<section id="pros-and-cons" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="pros-and-cons"><span class="header-section-number">6.4</span> Pros and cons</h2>
<p>Decision trees have several important advantages:</p>
<ul>
<li>Easy to interpret</li>
<li>Naturally handle nonlinear relationships</li>
<li>Automatically detect interactions</li>
<li>No need for feature scaling</li>
<li>Can handle both numerical and categorical predictors</li>
</ul>
<p>Decision trees also have important weaknesses:</p>
<ul>
<li>High variance</li>
<li>Sensitive to small changes in data</li>
<li>Often less accurate than ensemble methods</li>
<li>Deep trees may overfit severely</li>
</ul>
<p>Because of these weaknesses, single trees are often improved using ensemble methods such as:</p>
<ul>
<li>Bagging</li>
<li>Random forests</li>
<li>Boosting</li>
</ul>
</section>
<section id="tuning-hyperparameters" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="tuning-hyperparameters"><span class="header-section-number">6.5</span> Tuning hyperparameters</h2>
<p>Building a decision tree is the same as splitting the training dataset. If we are alllowed to keep splitting it, it is possible to get to a case that each end node is pure: the Gini impurity is 0, or every element has the same response variable locally. This means two things:</p>
<ol type="1">
<li>The tree learns too many (unnecessary) details from the training set so it is overfitting.</li>
<li>We could use the number of split to indicate the progress of the learning.</li>
</ol>
<p>In other words, the finer the splits are, the further the learning is. We need to consider some early stop conditions to prevent the model from overfitting.</p>
<p>Some possible early stop conditions:</p>
<ul>
<li><code>max_depth</code>: The max depth of the tree. <!-- - The default is `none` which means no limits. --></li>
<li><code>min_samples_split</code>: The minimum number of samples required to split an internal node. <!-- - The default is 2 which means that we will split a node with as few as 2 elements if needed. --></li>
<li><code>min_samples_leaf</code>: The minimum number of samples required to be at a leaf node. <!-- - The default is 1 which means that we will still split the node even if one subset only contains 1 element. --></li>
</ul>
<!-- If we don't set them (which means that we use the default setting), the dataset will be split untill all subsets are pure. -->
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.4 (ALMOST all end nodes are pure)</strong></span> In this example, we let the tree grow as further as possible. It only stops when (almost) all end nodes are pure, even if the end nodes only contain ONE element (like #6 and #11).</p>
<div id="01e87cf0" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-3-output-1.png" width="505" height="502" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In this example there is one exception. #13 node is not pure. We could list all data in node #13.</p>
<div id="c835ec31" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">x[0]</th>
<th data-quarto-table-cell-role="th">x[1]</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>4.8</td>
<td>1.8</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>4.8</td>
<td>1.8</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>4.8</td>
<td>1.8</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>All the data points in this node has the same feature while their labels are different. They cannot be split further purely based on features.</p>
</div>
<p>Therefore we could treat these hyperparameters as an indicator about how far the dataset is split. The further the dataset is split, the further the learning goes, the more details are learned. Since we don’t want the model to be overfitting, we don’t want to split the dataset that far. In this case, we could use the learning curve to help us make the decision.</p>
<p>In this example, let us choose <code>min_samples_leaf</code> as the indicator. When <code>min_samples_leaf</code> is big, the learning just starts. When <code>min_samples_leaf=1</code>, we reach the far most side of learning. We will see how the training and testing accuracy changes along the learning process.</p>
<div id="50167c2f" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.15</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>num_leaf <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">100</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>train_acc <span class="op">=</span> []</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>test_acc <span class="op">=</span> []</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> num_leaf:</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>, min_samples_leaf<span class="op">=</span>i)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    clf.fit(X_train, y_train)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    train_acc.append(clf.score(X_train, y_train))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    test_acc.append(clf.score(X_test, y_test))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.plot(num_leaf, train_acc, label<span class="op">=</span><span class="st">'training'</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>plt.plot(num_leaf, test_acc, label<span class="op">=</span><span class="st">'testing'</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>plt.gca().set_xlim((<span class="bu">max</span>(num_leaf)<span class="op">+</span><span class="dv">1</span>, <span class="bu">min</span>(num_leaf)<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-5-output-1.png" width="575" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From this plot, the accuracy has a big jump at <code>min_sample_leaf=41</code>. So we could choose this to be our hyperparameter.</p>
</section>
<section id="pruning" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="pruning"><span class="header-section-number">6.6</span> Pruning</h2>
<p>Other than tuning hyperparameters, we also want to prune our tree in order to reduce overfitting further. The pruning algorithm introduced together with CART is called <strong>Minimal-Cost-Complexity Pruning</strong> (MCCP).</p>
<p>The idea is to use the cost-complexity measure to replace Gini impurity to grow the tree. The cost-complexity measure is gotten by adding the total number of end nodes with the coefficent <code>ccp_alpha</code> to the Gini impurity. The parameter <code>ccp_alpha&gt;=0</code> is known as the <strong>complexity parameter</strong>, and it can help the tree to self-balance the number of end nodes and the Gini impurity.</p>
</section>
<section id="trees-in-python" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="trees-in-python"><span class="header-section-number">6.7</span> Trees in Python</h2>
<p>In <code>sklearn</code>, we use <code>cost_complexity_pruning_path</code> to help us find the effective alphas and the corresponding impurities.</p>
<div id="0631f1cb" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ccp_path <span class="op">=</span> clf.cost_complexity_pruning_path(X_train, y_train)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ccp_alphas, impurities <span class="op">=</span> ccp_path.ccp_alphas, ccp_path.impurities</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The list <code>ccp_alphas</code> contains all important <code>ccp_alpha</code>s. We could train a model for each of them. We could use the argument <code>ccp_alpha</code> to control the value when initialize the model. After we train all these tree models for each effective <code>ccp_alpha</code>, we evaluate the model and record the results.</p>
<div id="a68271d9" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>clfs <span class="op">=</span> []</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ccp_alpha <span class="kw">in</span> ccp_alphas:</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>, ccp_alpha<span class="op">=</span>ccp_alpha)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    clf.fit(X_train, y_train)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    clfs.append(clf)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>node_counts <span class="op">=</span> [clf.tree_.node_count <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>depth <span class="op">=</span> [clf.tree_.max_depth <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>train_acc <span class="op">=</span> [clf.score(X_train, y_train) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>test_acc <span class="op">=</span> [clf.score(X_test, y_test) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We would like to visualize these info.</p>
<div id="16febf16" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(ccp_alphas, node_counts, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">"number of nodes"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(ccp_alphas, depth, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">"depth of tree"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].plot(ccp_alphas, train_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].plot(ccp_alphas, test_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'test'</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_ylabel(<span class="st">"accuracy"</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].legend()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-8-output-1.png" width="597" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Based on the plot, it seems that the fourth dot 0.01534424 is a good fit. So this is the complexity parameter we are going to use.</p>
<details>
<summary>
We could combine all the code above into a function.
</summary>
<div id="493503fc" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.base <span class="im">import</span> clone</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> eval_ccp_alphas(clf, X, y):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    ccp_path <span class="op">=</span> clf.cost_complexity_pruning_path(X, y)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    ccp_alphas, impurities <span class="op">=</span> ccp_path.ccp_alphas, ccp_path.impurities</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    clfs <span class="op">=</span> []</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ccp_alpha <span class="kw">in</span> ccp_alphas:</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        clf_tmp <span class="op">=</span> clone(clf)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        clf_tmp.set_params(ccp_alpha<span class="op">=</span>ccp_alpha)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        clf_tmp.fit(X, y)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        clfs.append(clf_tmp)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    node_counts <span class="op">=</span> [clf.tree_.node_count <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    depth <span class="op">=</span> [clf.tree_.max_depth <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    train_acc <span class="op">=</span> [clf.score(X_train, y_train) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    test_acc <span class="op">=</span> [clf.score(X_test, y_test) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].plot(ccp_alphas, node_counts, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].set_ylabel(<span class="st">"number of nodes"</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].plot(ccp_alphas, depth, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].set_ylabel(<span class="st">"depth of tree"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].plot(ccp_alphas, train_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].plot(ccp_alphas, test_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'test'</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].set_ylabel(<span class="st">"accuracy"</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].legend()</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ccp_alphas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="04ad8cf8" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>eval_ccp_alphas(DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>), X_train, y_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array([0.        , 0.00485564, 0.01049869, 0.01534424, 0.03364964,
       0.24888323, 0.33214852])</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-10-output-2.png" width="597" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details>
</section>
<section id="tree" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Tree</h1>
<p>A decision tree is a nonparametric method. Instead of assuming a global linear form such as <span class="math display">\[
f(x)=\beta_0+\beta_1x_1+\cdots+\beta_px_p,
\]</span> a tree learns a collection of simple if-then rules from the data. A very typical example is shown below.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.1 (Classification Tree example)</strong></span> &nbsp;</p>
<div id="f5f62d64" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>[Text(0.4, 0.8333333333333334, 'node #0\nx[1] &lt;= 0.8\ngini = 0.667\nsamples = 150\nvalue = [50, 50, 50]'),
 Text(0.2, 0.5, 'node #1\ngini = 0.0\nsamples = 50\nvalue = [50, 0, 0]'),
 Text(0.30000000000000004, 0.6666666666666667, 'True  '),
 Text(0.6, 0.5, 'node #2\nx[1] &lt;= 1.75\ngini = 0.5\nsamples = 100\nvalue = [0, 50, 50]'),
 Text(0.5, 0.6666666666666667, '  False'),
 Text(0.4, 0.16666666666666666, 'node #3\ngini = 0.168\nsamples = 54\nvalue = [0, 49, 5]'),
 Text(0.8, 0.16666666666666666, 'node #4\ngini = 0.043\nsamples = 46\nvalue = [0, 1, 45]')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-11-output-2.png" width="505" height="502" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is a classficiation tree. In this example there are 3 classes, and we just check the feature <code>x[1]</code>. The first time if <code>x[1]&lt;=0.8</code>, the data will be classified as orange. If not, the tree will check <code>x[1]</code> again and compare it with 1.75. If this time it is <code>&lt;=1.75</code>, the data is classified as green, otherwise purple.</p>
</div>
<p>In general, a tree learns a collection of simple if-then rules from the data. A tree is called “adaptive” because the regions are learned from the data. If a predictor is useful, the tree may split on it many times. If a predictor is not useful, the tree may ignore it.</p>
<p>There are many algorithms for constructing decision trees. In this chapter, we focus on Classification and Regression Trees (usually called CART).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm: Split the Dataset
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Inputs</strong> Given a dataset <span class="math inline">\(S=\{[features, target]\}\)</span>.</p>
<p><strong>Outputs</strong> A best split <span class="math inline">\((k, t_k)\)</span>.</p>
<ol type="1">
<li>For each feature <span class="math inline">\(k\)</span>:
<ol type="1">
<li>For each value <span class="math inline">\(t\)</span> of the feature:
<ol type="1">
<li>Split the dataset <span class="math inline">\(S\)</span> into two subsets, one with <span class="math inline">\(k\leq t\)</span> and one with <span class="math inline">\(k&gt;t\)</span>.</li>
<li>Compute the cost function <span class="math inline">\(J(k,t)\)</span>.</li>
<li>Compare it with the current smallest cost. If this split has smaller cost, replace the current smallest cost and pair with <span class="math inline">\((k, t)\)</span>.</li>
</ol></li>
</ol></li>
<li>Return the pair <span class="math inline">\((k,t_k)\)</span> that has the smallest cost function.</li>
</ol>
</div>
</div>
<p>We then use this split algorithm recursively to get the decision tree.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Classification and Regression Tree, CART
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Inputs</strong> Given a labeled dataset <span class="math inline">\(S=\{[features, label]\}\)</span> and a maximal depth <code>max_depth</code>.</p>
<p><strong>Outputs</strong> A decision tree.</p>
<ol type="1">
<li>Starting from the original dataset <span class="math inline">\(S\)</span>. Set the working dataset <span class="math inline">\(G=S\)</span>.</li>
<li>Consider a dataset <span class="math inline">\(G\)</span>. If the cost function <span class="math inline">\(J(G)\neq0\)</span>, split <span class="math inline">\(G\)</span> into <span class="math inline">\(G_l\)</span> and <span class="math inline">\(G_r\)</span> to minimize the cost function. Record the split pair <span class="math inline">\((k, t_k)\)</span>.</li>
<li>Now set the working dataset <span class="math inline">\(G=G_l\)</span> and <span class="math inline">\(G=G_r\)</span> respectively, and apply the above two steps to each of them.</li>
<li>Repeat the above steps, until <code>max_depth</code> is reached, or each subset is pure that is impossible to split further.</li>
</ol>
</div>
</div>
<p>CART has the following features:</p>
<ul>
<li>It creates only binary splits.</li>
<li>For classification, common splitting criteria include Gini impurity and entropy.</li>
<li>For regression, common splitting criteria include mean squared error or sum of squared errors.</li>
</ul>
<section id="classification-tree" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="classification-tree"><span class="header-section-number">7.1</span> Classification Tree</h2>
<section id="gini-impurity-2" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="gini-impurity-2"><span class="header-section-number">7.1.1</span> Gini impurity</h3>
<p>To split a dataset, we need a metric to tell whether the split is good or not. The two most popular metrics that are used are Gini impurity and Entropy. The two metrics don’t have essential differences, that the results obtained by applying each metric are very similar to each other. Therefore we will only focus on Gini impurity since it is slightly easier to compute and slightly easier to explain.</p>
<!-- ### Motivation and Definition -->
<p>Assume that we have a dataset of totally <span class="math inline">\(n\)</span> objects, and these objects are divided into <span class="math inline">\(k\)</span> classes. The <span class="math inline">\(i\)</span>-th class has <span class="math inline">\(n_i\)</span> objects. Then if we randomly pick an object, the probability to get an object belonging to the <span class="math inline">\(i\)</span>-th class is</p>
<p><span class="math display">\[
p_i=\frac{n_i}{n}
\]</span></p>
<p>If we then guess the class of the object purely based on the distribution of each class, the probability that our guess is incorrect is</p>
<p><span class="math display">\[
1-p_i = 1-\frac{n_i}{n}.
\]</span></p>
<p>Therefore, if we randomly pick an object that belongs to the <span class="math inline">\(i\)</span>-th class and randomly guess its class purely based on the distribution but our guess is wrong, the probability that such a thing happens is</p>
<p><span class="math display">\[
p_i(1-p_i).
\]</span></p>
<p>Consider all classes. The probability at which any object of the dataset will be mislabelled when it is randomly labeled is the sum of the probability described above:</p>
<p><span class="math display">\[
\sum_{i=1}^kp_i(1-p_i)=\sum_{i=1}^kp_i-\sum_{i=1}^kp_i^2=1-\sum_{i=1}^kp_i^2.
\]</span></p>
<p>This is the definition formula for the <em>Gini impurity</em>.</p>
<div id="def-gini" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 7.1</strong></span> The <strong>Gini impurity</strong> is calculated using the following formula</p>
<p><span class="math display">\[
Gini = \sum_{i=1}^kp_i(1-p_i)=\sum_{i=1}^kp_i-\sum_{i=1}^kp_i^2=1-\sum_{i=1}^kp_i^2,
\]</span> where <span class="math inline">\(p_i\)</span> is the probability of class <span class="math inline">\(i\)</span>.</p>
</div>
<p>The way to understand Gini impurity is to consider some extreme examples.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.2</strong></span> Assume that we only have one class. Therefore <span class="math inline">\(k=1\)</span>, and <span class="math inline">\(p_1=1\)</span>. Then the Gini impurity is</p>
<p><span class="math display">\[
Gini = 1-1^2=0.
\]</span> This is the minimum possible Gini impurity. It means that the dataset is <strong>pure</strong>: all the objects contained are of one unique class. In this case, we won’t make any mistakes if we randomly guess the label.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.3</strong></span> Assume that we have two classes. Therefore <span class="math inline">\(k=2\)</span>. Consider the distribution <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>. We know that <span class="math inline">\(p_1+p_2=1\)</span>. Therefore <span class="math inline">\(p_2=1-p_1\)</span>. Then the Gini impurity is</p>
<p><span class="math display">\[
Gini(p_1) = 1-p_1^2-p_2^2=1-p_1^2-(1-p_1)^2=2p_1-2p_1^2.
\]</span> When <span class="math inline">\(0\leq p_1\leq 1\)</span>, this function <span class="math inline">\(Gini(p_1)\)</span> is between <span class="math inline">\(0\)</span> and <span class="math inline">\(0.5\)</span>. - It gets <span class="math inline">\(0\)</span> when <span class="math inline">\(p_1=0\)</span> or <span class="math inline">\(1\)</span>. In these two cases, the dataset is still a one-class set since the size of one class is <span class="math inline">\(0\)</span>. - It gets <span class="math inline">\(0.5\)</span> when <span class="math inline">\(p_1=0.5\)</span>. This means that the Gini impurity is maximized when the size of different classes are balanced.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Entropy
</div>
</div>
<div class="callout-body-container callout-body">
<p>Other than Gini impurity, entropy is also a popular choice for classification tree. However its performance is very similar to the Gini impurity while the formula for entropy is a little bit more complicated, therefore we only discuss the Gini impurity in this notes.</p>
</div>
</div>
<!-- ### Algorithm


::: {.callout-note}
# Algorithm: Gini impurity

**Inputs** A dataset $S=\{data=[features, label]\}$ with labels. 

**Outputs** The Gini impurity of the dataset.

1. Get the size $n$ of the dataset.
2. Go through the label list, and find all unique labels: $uniqueLabelList$.
3. Go through each label $l$ in $uniqueLabelList$ and count how many elements belonging to the label, and record them as $n_l$.
4. Use the formula to compute the Gini impurity:

   $$
    Gini = 1-\sum_{l\in uniqueLabelList}\left(\frac{n_l}{n}\right)^2.
   $$
:::
 -->
<p>Suppose the tree divides the feature space into <span class="math inline">\(M\)</span> terminal regions: <span class="math display">\[
R_1,R_2,\ldots,R_M.
\]</span></p>
<p>These regions are also called leaves or terminal nodes.</p>
<p>For a new observation <span class="math inline">\(x\)</span>, the fitted regression tree has the form <span class="math display">\[
\hat f(x)=\sum_{m=1}^M c_m I(x\in R_m),
\]</span> where <span class="math inline">\(c_m\)</span> is the prediction assigned to region <span class="math inline">\(R_m\)</span>.</p>
<p>For squared error loss, the best constant in each region is the sample mean: <span class="math display">\[
\hat c_m
=
\frac{1}{N_m}
\sum_{x_i\in R_m}y_i,
\]</span> where <span class="math inline">\(N_m\)</span> is the number of training observations in region <span class="math inline">\(R_m\)</span>.</p>
<p>Therefore, <span class="math display">\[
\hat f(x)
=
\sum_{m=1}^M
\bar y_{R_m} I(x\in R_m).
\]</span></p>
<p>This is a piecewise constant approximation to the regression function <span class="math inline">\(f(x)=E(Y\mid X=x)\)</span>.</p>
<p>Inside a leaf, every point receives the same prediction. Across a split boundary, the prediction can jump.</p>
</section>
</section>
<section id="a-single-split" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="a-single-split"><span class="header-section-number">7.2</span> 3. A single split</h2>
<p>At a node <span class="math inline">\(\mathcal A\)</span>, a binary split is determined by:</p>
<ul>
<li>a variable index <span class="math inline">\(j\)</span></li>
<li>a cutoff value <span class="math inline">\(c\)</span></li>
</ul>
<p>The split creates two child nodes: <span class="math display">\[
\mathcal A_L(j,c)=\{x\in \mathcal A: x_j\le c\},
\]</span> and <span class="math display">\[
\mathcal A_R(j,c)=\{x\in \mathcal A: x_j&gt;c\}.
\]</span></p>
<p>For regression, a good split makes the responses inside each child node more homogeneous.</p>
<p>One way to write the split criterion is the weighted post-split variance: <span class="math display">\[
\frac{N_L}{N_{\mathcal A}}\operatorname{Var}(\mathcal A_L)
+
\frac{N_R}{N_{\mathcal A}}\operatorname{Var}(\mathcal A_R).
\]</span></p>
<p>We want this quantity to be small.</p>
<p>Equivalently, we maximize the variance reduction: <span class="math display">\[
\operatorname{score}(j,c)
=
\operatorname{Var}(\mathcal A)
-
\left[
\frac{N_L}{N_{\mathcal A}}\operatorname{Var}(\mathcal A_L)
+
\frac{N_R}{N_{\mathcal A}}\operatorname{Var}(\mathcal A_R)
\right].
\]</span></p>
<p>The best split is <span class="math display">\[
(\hat j,\hat c)
=
\arg\max_{j,c}\operatorname{score}(j,c).
\]</span></p>
<p>The same idea can be written using residual sum of squares: <span class="math display">\[
\sum_{x_i\in \mathcal A_L}(y_i-\bar y_L)^2
+
\sum_{x_i\in \mathcal A_R}(y_i-\bar y_R)^2.
\]</span></p>
<p>The split with the smallest post-split RSS is chosen.</p>
</section>
<section id="recursive-binary-splitting" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="recursive-binary-splitting"><span class="header-section-number">7.3</span> 4. Recursive binary splitting</h2>
<p>A regression tree is built greedily.</p>
<p>At each node:</p>
<ol type="1">
<li>Try each predictor <span class="math inline">\(x_j\)</span>.</li>
<li>Try candidate cutoffs <span class="math inline">\(c\)</span>.</li>
<li>Compute the split criterion.</li>
<li>Choose the split with the largest reduction in RSS.</li>
<li>Repeat the same procedure on the two child nodes.</li>
</ol>
<p>This is called recursive binary splitting.</p>
<p>The procedure is greedy because the best split is chosen locally at each step. The algorithm does not search over all possible trees globally.</p>
<p>This matters because an early split affects all later splits below it. A split that looks best now may not be part of the globally best tree.</p>
<p>Still, recursive binary splitting is fast, simple, and usually effective.</p>
</section>
<section id="candidate-cutoffs" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="candidate-cutoffs"><span class="header-section-number">7.4</span> 5. Candidate cutoffs</h2>
<p>For a continuous predictor <span class="math inline">\(x_j\)</span>, candidate cutoffs are usually chosen between sorted observed values.</p>
<p>If the unique observed values of <span class="math inline">\(x_j\)</span> are <span class="math display">\[
v_1&lt;v_2&lt;\cdots&lt;v_K,
\]</span> then possible cutoffs can be taken as midpoints: <span class="math display">\[
c_k=\frac{v_k+v_{k+1}}{2},
\qquad k=1,\ldots,K-1.
\]</span></p>
<p>For each candidate cutoff, the data in the current node are divided into a left group and a right group.</p>
<p>For categorical predictors, a split divides the categories into two groups. In practice, software handles this differently depending on the implementation. Some implementations require one-hot encoding first.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Practical detail
</div>
</div>
<div class="callout-body-container callout-body">
<p>Trees do not require variables to be on the same scale.</p>
<p>A split only compares one variable to one cutoff, so standardization is usually not needed for ordinary tree models.</p>
</div>
</div>
</section>
<section id="prediction" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="prediction"><span class="header-section-number">7.5</span> 6. Prediction</h2>
<p>Once the tree is fitted, prediction is simple.</p>
<p>For a new point <span class="math inline">\(x_0\)</span>:</p>
<ol type="1">
<li>Start at the root node.</li>
<li>Follow the splitting rules.</li>
<li>Drop <span class="math inline">\(x_0\)</span> into a terminal node <span class="math inline">\(R_m\)</span>.</li>
<li>Predict by the average response in that leaf:</li>
</ol>
<p><span class="math display">\[
\hat f(x_0)=\bar y_{R_m}.
\]</span></p>
<p>Equivalently, <span class="math display">\[
\hat f(x_0)
=
\sum_{m=1}^M
\left(
\frac{\sum_{i=1}^n y_i I(x_i\in R_m)}
{\sum_{i=1}^n I(x_i\in R_m)}
\right)
I(x_0\in R_m).
\]</span></p>
<p>This expression shows that a regression tree is a local averaging estimator.</p>
<p>The neighborhood of <span class="math inline">\(x_0\)</span> is not a ball or a nearest-neighbor set. It is the leaf containing <span class="math inline">\(x_0\)</span>.</p>
</section>
<section id="adaptive-kernel-view" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="adaptive-kernel-view"><span class="header-section-number">7.6</span> 7. Adaptive kernel view</h2>
<p>KNN also predicts by local averaging, but its neighborhood is usually determined by distance.</p>
<p>A tree also predicts by averaging nearby training responses, but the neighborhood is defined by the learned terminal node.</p>
<p>Let <span class="math inline">\(R(x_0)\)</span> be the terminal node containing <span class="math inline">\(x_0\)</span>.</p>
<p>For a point <span class="math inline">\(x_0\)</span>, the tree gives positive weight only to observations that fall in the same terminal node: <span class="math display">\[
w_i(x_0)
=
\frac{I(x_i\in R(x_0))}
{\sum_{l=1}^n I(x_l\in R(x_0))}.
\]</span></p>
<p>Then <span class="math display">\[
\hat f(x_0)=\sum_{i=1}^n w_i(x_0)y_i.
\]</span></p>
<p>The important difference is that the tree neighborhood is adaptive.</p>
<p>If only <span class="math inline">\(x_1\)</span> is important, the tree may split mostly on <span class="math inline">\(x_1\)</span> and ignore irrelevant directions. This helps trees avoid some problems of ordinary distance-based local methods.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>KNN uses a fixed notion of distance.</p>
<p>A tree learns the neighborhood from the data.</p>
</div>
</div>
</section>
<section id="geometry" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="geometry"><span class="header-section-number">7.7</span> 8. Geometry</h2>
<p>A regression tree partitions the feature space into axis-aligned rectangles.</p>
<p>For example, in two dimensions, a split such as <span class="math display">\[
x_1\le c
\]</span> creates a vertical boundary, and a split such as <span class="math display">\[
x_2\le c
\]</span> creates a horizontal boundary.</p>
<p>After several splits, the feature space becomes a collection of rectangles.</p>
<p>Inside each rectangle, the fitted value is constant: <span class="math display">\[
\hat f(x)=\bar y_R.
\]</span></p>
<p>Therefore, trees can model nonlinear patterns and interactions, but the fitted function is not smooth.</p>
<p>The function is flat inside each region and jumps across split boundaries.</p>
<p>This is why a single tree often looks rough.</p>
</section>
<section id="interactions" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="interactions"><span class="header-section-number">7.8</span> 9. Interactions</h2>
<p>Trees handle interactions naturally.</p>
<p>An interaction means the effect of one variable depends on the value of another variable.</p>
<p>For example, suppose the tree first splits on <span class="math inline">\(x_1\)</span>: <span class="math display">\[
x_1\le c_1.
\]</span></p>
<p>Then, inside the left branch, the tree may split on <span class="math inline">\(x_2\)</span>: <span class="math display">\[
x_2\le c_2.
\]</span></p>
<p>This means the role of <span class="math inline">\(x_2\)</span> is different depending on whether <span class="math inline">\(x_1\le c_1\)</span> or <span class="math inline">\(x_1&gt;c_1\)</span>.</p>
<p>No explicit interaction term such as <span class="math inline">\(x_1x_2\)</span> needs to be added.</p>
<p>This is one reason trees are useful exploratory models.</p>
</section>
<section id="cart-algorithms" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="cart-algorithms"><span class="header-section-number">7.9</span> CART Algorithms</h2>
<section id="ideas" class="level3" data-number="7.9.1">
<h3 data-number="7.9.1" class="anchored" data-anchor-id="ideas"><span class="header-section-number">7.9.1</span> Ideas</h3>
<p>Consider a labeled dataset <span class="math inline">\(S\)</span> with totally <span class="math inline">\(m\)</span> elements. We use a feature <span class="math inline">\(k\)</span> and a threshold <span class="math inline">\(t_k\)</span> to split it into two subsets: <span class="math inline">\(S_l\)</span> with <span class="math inline">\(m_l\)</span> elements and <span class="math inline">\(S_r\)</span> with <span class="math inline">\(m_r\)</span> elements. Then the cost function of this split is</p>
<p><span class="math display">\[
J(k, t_k)=\frac{m_l}mGini(S_l)+\frac{m_r}{m}Gini(S_r).
\]</span> It is not hard to see that the more pure the two subsets are the lower the cost function is. Therefore our goal is find a split that can minimize the cost function.</p>
</section>
</section>
<section id="decision-tree-project-1-the-iris-dataset" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="decision-tree-project-1-the-iris-dataset"><span class="header-section-number">7.10</span> Decision Tree Project 1: the <code>iris</code> dataset</h2>
<p>We are going to use the Decision Tree model to study the <code>iris</code> dataset. This dataset has already studied previously using k-NN. Again we will only use the first two features for visualization purpose.</p>
<section id="initial-setup" class="level3" data-number="7.10.1">
<h3 data-number="7.10.1" class="anchored" data-anchor-id="initial-setup"><span class="header-section-number">7.10.1</span> Initial setup</h3>
<p>Since the dataset will be splitted, we will put <code>X</code> and <code>y</code> together as a single variable <code>S</code>. In this case when we split the dataset by selecting rows, the features and the labels are still paired correctly.</p>
<p>We also print the labels and the feature names for our convenience.</p>
<div id="e660ea34" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> load_iris</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>iris <span class="op">=</span> load_iris()</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> iris.data[:, <span class="dv">2</span>:]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> iris.target</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> y.reshape((y.shape[<span class="dv">0</span>],<span class="dv">1</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>S <span class="op">=</span> np.concatenate([X,y], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iris.target_names)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iris.feature_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']</code></pre>
</div>
</div>
</section>
<section id="use-package-sklearn" class="level3" data-number="7.10.2">
<h3 data-number="7.10.2" class="anchored" data-anchor-id="use-package-sklearn"><span class="header-section-number">7.10.2</span> Use package <code>sklearn</code></h3>
<p>Now we would like to use the decision tree package provided by <code>sklearn</code>. The process is straightforward. The parameter <code>random_state=40</code> will be discussed {ref}<code>later&lt;note-random_state&gt;</code>, and it is not necessary in most cases.</p>
<div id="c3e46640" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">40</span>, min_samples_split<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>clf.fit(X, y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<style>#sk-container-id-1 {
  /* Definition of color scheme common for light and dark mode */
  --sklearn-color-text: #000;
  --sklearn-color-text-muted: #666;
  --sklearn-color-line: gray;
  /* Definition of color scheme for unfitted estimators */
  --sklearn-color-unfitted-level-0: #fff5e6;
  --sklearn-color-unfitted-level-1: #f6e4d2;
  --sklearn-color-unfitted-level-2: #ffe0b3;
  --sklearn-color-unfitted-level-3: chocolate;
  /* Definition of color scheme for fitted estimators */
  --sklearn-color-fitted-level-0: #f0f8ff;
  --sklearn-color-fitted-level-1: #d4ebff;
  --sklearn-color-fitted-level-2: #b3dbfd;
  --sklearn-color-fitted-level-3: cornflowerblue;
}

#sk-container-id-1.light {
  /* Specific color for light theme */
  --sklearn-color-text-on-default-background: black;
  --sklearn-color-background: white;
  --sklearn-color-border-box: black;
  --sklearn-color-icon: #696969;
}

#sk-container-id-1.dark {
  --sklearn-color-text-on-default-background: white;
  --sklearn-color-background: #111;
  --sklearn-color-border-box: white;
  --sklearn-color-icon: #878787;
}

#sk-container-id-1 {
  color: var(--sklearn-color-text);
}

#sk-container-id-1 pre {
  padding: 0;
}

#sk-container-id-1 input.sk-hidden--visually {
  border: 0;
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

#sk-container-id-1 div.sk-dashed-wrapped {
  border: 1px dashed var(--sklearn-color-line);
  margin: 0 0.4em 0.5em 0.4em;
  box-sizing: border-box;
  padding-bottom: 0.4em;
  background-color: var(--sklearn-color-background);
}

#sk-container-id-1 div.sk-container {
  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`
     but bootstrap.min.css set `[hidden] { display: none !important; }`
     so we also need the `!important` here to be able to override the
     default hidden behavior on the sphinx rendered scikit-learn.org.
     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */
  display: inline-block !important;
  position: relative;
}

#sk-container-id-1 div.sk-text-repr-fallback {
  display: none;
}

div.sk-parallel-item,
div.sk-serial,
div.sk-item {
  /* draw centered vertical line to link estimators */
  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));
  background-size: 2px 100%;
  background-repeat: no-repeat;
  background-position: center center;
}

/* Parallel-specific style estimator block */

#sk-container-id-1 div.sk-parallel-item::after {
  content: "";
  width: 100%;
  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);
  flex-grow: 1;
}

#sk-container-id-1 div.sk-parallel {
  display: flex;
  align-items: stretch;
  justify-content: center;
  background-color: var(--sklearn-color-background);
  position: relative;
}

#sk-container-id-1 div.sk-parallel-item {
  display: flex;
  flex-direction: column;
}

#sk-container-id-1 div.sk-parallel-item:first-child::after {
  align-self: flex-end;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:last-child::after {
  align-self: flex-start;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:only-child::after {
  width: 0;
}

/* Serial-specific style estimator block */

#sk-container-id-1 div.sk-serial {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--sklearn-color-background);
  padding-right: 1em;
  padding-left: 1em;
}


/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is
clickable and can be expanded/collapsed.
- Pipeline and ColumnTransformer use this feature and define the default style
- Estimators will overwrite some part of the style using the `sk-estimator` class
*/

/* Pipeline and ColumnTransformer style (default) */

#sk-container-id-1 div.sk-toggleable {
  /* Default theme specific background. It is overwritten whether we have a
  specific estimator or a Pipeline/ColumnTransformer */
  background-color: var(--sklearn-color-background);
}

/* Toggleable label */
#sk-container-id-1 label.sk-toggleable__label {
  cursor: pointer;
  display: flex;
  width: 100%;
  margin-bottom: 0;
  padding: 0.5em;
  box-sizing: border-box;
  text-align: center;
  align-items: center;
  justify-content: center;
  gap: 0.5em;
}

#sk-container-id-1 label.sk-toggleable__label .caption {
  font-size: 0.6rem;
  font-weight: lighter;
  color: var(--sklearn-color-text-muted);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:before {
  /* Arrow on the left of the label */
  content: "▸";
  float: left;
  margin-right: 0.25em;
  color: var(--sklearn-color-icon);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {
  color: var(--sklearn-color-text);
}

/* Toggleable content - dropdown */

#sk-container-id-1 div.sk-toggleable__content {
  display: none;
  text-align: left;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content pre {
  margin: 0.2em;
  border-radius: 0.25em;
  color: var(--sklearn-color-text);
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted pre {
  /* unfitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {
  /* Expand drop-down */
  display: block;
  width: 100%;
  overflow: visible;
}

#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {
  content: "▾";
}

/* Pipeline/ColumnTransformer-specific style */

#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator-specific style */

/* Colorize estimator box */
#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

#sk-container-id-1 div.sk-label label.sk-toggleable__label,
#sk-container-id-1 div.sk-label label {
  /* The background is the default theme color */
  color: var(--sklearn-color-text-on-default-background);
}

/* On hover, darken the color of the background */
#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

/* Label box, darken color on hover, fitted */
#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator label */

#sk-container-id-1 div.sk-label label {
  font-family: monospace;
  font-weight: bold;
  line-height: 1.2em;
}

#sk-container-id-1 div.sk-label-container {
  text-align: center;
}

/* Estimator-specific */
#sk-container-id-1 div.sk-estimator {
  font-family: monospace;
  border: 1px dotted var(--sklearn-color-border-box);
  border-radius: 0.25em;
  box-sizing: border-box;
  margin-bottom: 0.5em;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-estimator.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

/* on hover */
#sk-container-id-1 div.sk-estimator:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Specification for estimator info (e.g. "i" and "?") */

/* Common style for "i" and "?" */

.sk-estimator-doc-link,
a:link.sk-estimator-doc-link,
a:visited.sk-estimator-doc-link {
  float: right;
  font-size: smaller;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1em;
  height: 1em;
  width: 1em;
  text-decoration: none !important;
  margin-left: 0.5em;
  text-align: center;
  /* unfitted */
  border: var(--sklearn-color-unfitted-level-3) 1pt solid;
  color: var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted,
a:link.sk-estimator-doc-link.fitted,
a:visited.sk-estimator-doc-link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3) 1pt solid;
  color: var(--sklearn-color-fitted-level-3);
}

/* On hover */
div.sk-estimator:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover,
div.sk-label-container:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-unfitted-level-0);
  text-decoration: none;
}

div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover,
div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-fitted-level-0);
  text-decoration: none;
}

/* Span, style for the box shown on hovering the info icon */
.sk-estimator-doc-link span {
  display: none;
  z-index: 9999;
  position: relative;
  font-weight: normal;
  right: .2ex;
  padding: .5ex;
  margin: .5ex;
  width: min-content;
  min-width: 20ex;
  max-width: 50ex;
  color: var(--sklearn-color-text);
  box-shadow: 2pt 2pt 4pt #999;
  /* unfitted */
  background: var(--sklearn-color-unfitted-level-0);
  border: .5pt solid var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted span {
  /* fitted */
  background: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3);
}

.sk-estimator-doc-link:hover span {
  display: block;
}

/* "?"-specific style due to the `<a>` HTML tag */

#sk-container-id-1 a.estimator_doc_link {
  float: right;
  font-size: 1rem;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1rem;
  height: 1rem;
  width: 1rem;
  text-decoration: none;
  /* unfitted */
  color: var(--sklearn-color-unfitted-level-1);
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
}

#sk-container-id-1 a.estimator_doc_link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
#sk-container-id-1 a.estimator_doc_link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

#sk-container-id-1 a.estimator_doc_link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
}

.estimator-table {
    font-family: monospace;
}

.estimator-table summary {
    padding: .5rem;
    cursor: pointer;
}

.estimator-table summary::marker {
    font-size: 0.7rem;
}

.estimator-table details[open] {
    padding-left: 0.1rem;
    padding-right: 0.1rem;
    padding-bottom: 0.3rem;
}

.estimator-table .parameters-table {
    margin-left: auto !important;
    margin-right: auto !important;
    margin-top: 0;
}

.estimator-table .parameters-table tr:nth-child(odd) {
    background-color: #fff;
}

.estimator-table .parameters-table tr:nth-child(even) {
    background-color: #f6f6f6;
}

.estimator-table .parameters-table tr:hover {
    background-color: #e0e0e0;
}

.estimator-table table td {
    border: 1px solid rgba(106, 105, 104, 0.232);
}

/*
    `table td`is set in notebook with right text-align.
    We need to overwrite it.
*/
.estimator-table table td.param {
    text-align: left;
    position: relative;
    padding: 0;
}

.user-set td {
    color:rgb(255, 94, 0);
    text-align: left !important;
}

.user-set td.value {
    color:rgb(255, 94, 0);
    background-color: transparent;
}

.default td {
    color: black;
    text-align: left !important;
}

.user-set td i,
.default td i {
    color: black;
}

/*
    Styles for parameter documentation links
    We need styling for visited so jupyter doesn't overwrite it
*/
a.param-doc-link,
a.param-doc-link:link,
a.param-doc-link:visited {
    text-decoration: underline dashed;
    text-underline-offset: .3em;
    color: inherit;
    display: block;
    padding: .5em;
}

/* "hack" to make the entire area of the cell containing the link clickable */
a.param-doc-link::before {
    position: absolute;
    content: "";
    inset: 0;
}

.param-doc-description {
    display: none;
    position: absolute;
    z-index: 9999;
    left: 0;
    padding: .5ex;
    margin-left: 1.5em;
    color: var(--sklearn-color-text);
    box-shadow: .3em .3em .4em #999;
    width: max-content;
    text-align: left;
    max-height: 10em;
    overflow-y: auto;

    /* unfitted */
    background: var(--sklearn-color-unfitted-level-0);
    border: thin solid var(--sklearn-color-unfitted-level-3);
}

/* Fitted state for parameter tooltips */
.fitted .param-doc-description {
    /* fitted */
    background: var(--sklearn-color-fitted-level-0);
    border: thin solid var(--sklearn-color-fitted-level-3);
}

.param-doc-link:hover .param-doc-description {
    display: block;
}

.copy-paste-icon {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);
    background-repeat: no-repeat;
    background-size: 14px 14px;
    background-position: 0;
    display: inline-block;
    width: 14px;
    height: 14px;
    cursor: pointer;
}
</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>DecisionTreeClassifier(random_state=40)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>DecisionTreeClassifier</div></div><div><a class="sk-estimator-doc-link fitted" rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html">?<span>Documentation for DecisionTreeClassifier</span></a><span class="sk-estimator-doc-link fitted">i<span>Fitted</span></span></div></label><div class="sk-toggleable__content fitted" data-param-prefix="">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=criterion,-%7B%22gini%22%2C%20%22entropy%22%2C%20%22log_loss%22%7D%2C%20default%3D%22gini%22" class="param-doc-link" rel="noreferrer" target="_blank">criterion <span class="param-doc-description">criterion: {"gini", "entropy", "log_loss"}, default="gini"<br>
<br>
The function to measure the quality of a split. Supported criteria are<br>
"gini" for the Gini impurity and "log_loss" and "entropy" both for the<br>
Shannon information gain, see :ref:`tree_mathematical_formulation`.</span></a></td>
<td class="value">'gini'</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=splitter,-%7B%22best%22%2C%20%22random%22%7D%2C%20default%3D%22best%22" class="param-doc-link" rel="noreferrer" target="_blank">splitter <span class="param-doc-description">splitter: {"best", "random"}, default="best"<br>
<br>
The strategy used to choose the split at each node. Supported<br>
strategies are "best" to choose the best split and "random" to choose<br>
the best random split.</span></a></td>
<td class="value">'best'</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=max_depth,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_depth <span class="param-doc-description">max_depth: int, default=None<br>
<br>
The maximum depth of the tree. If None, then nodes are expanded until<br>
all leaves are pure or until all leaves contain less than<br>
min_samples_split samples.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=min_samples_split,-int%20or%20float%2C%20default%3D2" class="param-doc-link" rel="noreferrer" target="_blank">min_samples_split <span class="param-doc-description">min_samples_split: int or float, default=2<br>
<br>
The minimum number of samples required to split an internal node:<br>
<br>
- If int, then consider `min_samples_split` as the minimum number.<br>
- If float, then `min_samples_split` is a fraction and<br>
`ceil(min_samples_split * n_samples)` are the minimum<br>
number of samples for each split.<br>
<br>
.. versionchanged:: 0.18<br>
Added float values for fractions.</span></a></td>
<td class="value">2</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=min_samples_leaf,-int%20or%20float%2C%20default%3D1" class="param-doc-link" rel="noreferrer" target="_blank">min_samples_leaf <span class="param-doc-description">min_samples_leaf: int or float, default=1<br>
<br>
The minimum number of samples required to be at a leaf node.<br>
A split point at any depth will only be considered if it leaves at<br>
least ``min_samples_leaf`` training samples in each of the left and<br>
right branches. This may have the effect of smoothing the model,<br>
especially in regression.<br>
<br>
- If int, then consider `min_samples_leaf` as the minimum number.<br>
- If float, then `min_samples_leaf` is a fraction and<br>
`ceil(min_samples_leaf * n_samples)` are the minimum<br>
number of samples for each node.<br>
<br>
.. versionchanged:: 0.18<br>
Added float values for fractions.</span></a></td>
<td class="value">1</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=min_weight_fraction_leaf,-float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">min_weight_fraction_leaf <span class="param-doc-description">min_weight_fraction_leaf: float, default=0.0<br>
<br>
The minimum weighted fraction of the sum total of weights (of all<br>
the input samples) required to be at a leaf node. Samples have<br>
equal weight when sample_weight is not provided.</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=max_features,-int%2C%20float%20or%20%7B%22sqrt%22%2C%20%22log2%22%7D%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_features <span class="param-doc-description">max_features: int, float or {"sqrt", "log2"}, default=None<br>
<br>
The number of features to consider when looking for the best split:<br>
<br>
- If int, then consider `max_features` features at each split.<br>
- If float, then `max_features` is a fraction and<br>
`max(1, int(max_features * n_features_in_))` features are considered at<br>
each split.<br>
- If "sqrt", then `max_features=sqrt(n_features)`.<br>
- If "log2", then `max_features=log2(n_features)`.<br>
- If None, then `max_features=n_features`.<br>
<br>
.. note::<br>
<br>
The search for a split does not stop until at least one<br>
valid partition of the node samples is found, even if it requires to<br>
effectively inspect more than ``max_features`` features.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="user-set even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=random_state,-int%2C%20RandomState%20instance%20or%20None%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">random_state <span class="param-doc-description">random_state: int, RandomState instance or None, default=None<br>
<br>
Controls the randomness of the estimator. The features are always<br>
randomly permuted at each split, even if ``splitter`` is set to<br>
``"best"``. When ``max_features &lt; n_features``, the algorithm will<br>
select ``max_features`` at random at each split before finding the best<br>
split among them. But the best found split may vary across different<br>
runs, even if ``max_features=n_features``. That is the case, if the<br>
improvement of the criterion is identical for several splits and one<br>
split has to be selected at random. To obtain a deterministic behaviour<br>
during fitting, ``random_state`` has to be fixed to an integer.<br>
See :term:`Glossary <random_state>` for details.</random_state></span></a></td>
<td class="value">40</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=max_leaf_nodes,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_leaf_nodes <span class="param-doc-description">max_leaf_nodes: int, default=None<br>
<br>
Grow a tree with ``max_leaf_nodes`` in best-first fashion.<br>
Best nodes are defined as relative reduction in impurity.<br>
If None then unlimited number of leaf nodes.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=min_impurity_decrease,-float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">min_impurity_decrease <span class="param-doc-description">min_impurity_decrease: float, default=0.0<br>
<br>
A node will be split if this split induces a decrease of the impurity<br>
greater than or equal to this value.<br>
<br>
The weighted impurity decrease equation is the following::<br>
<br>
N_t / N * (impurity - N_t_R / N_t * right_impurity<br>
- N_t_L / N_t * left_impurity)<br>
<br>
where ``N`` is the total number of samples, ``N_t`` is the number of<br>
samples at the current node, ``N_t_L`` is the number of samples in the<br>
left child, and ``N_t_R`` is the number of samples in the right child.<br>
<br>
``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,<br>
if ``sample_weight`` is passed.<br>
<br>
.. versionadded:: 0.19</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=class_weight,-dict%2C%20list%20of%20dict%20or%20%22balanced%22%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">class_weight <span class="param-doc-description">class_weight: dict, list of dict or "balanced", default=None<br>
<br>
Weights associated with classes in the form ``{class_label: weight}``.<br>
If None, all classes are supposed to have weight one. For<br>
multi-output problems, a list of dicts can be provided in the same<br>
order as the columns of y.<br>
<br>
Note that for multioutput (including multilabel) weights should be<br>
defined for each class of every column in its own dict. For example,<br>
for four-class multilabel classification weights should be<br>
[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of<br>
[{1:1}, {2:5}, {3:1}, {4:1}].<br>
<br>
The "balanced" mode uses the values of y to automatically adjust<br>
weights inversely proportional to class frequencies in the input data<br>
as ``n_samples / (n_classes * np.bincount(y))``<br>
<br>
For multi-output, the weights of each column of y will be multiplied.<br>
<br>
Note that these weights will be multiplied with sample_weight (passed<br>
through the fit method) if sample_weight is specified.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=ccp_alpha,-non-negative%20float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">ccp_alpha <span class="param-doc-description">ccp_alpha: non-negative float, default=0.0<br>
<br>
Complexity parameter used for Minimal Cost-Complexity Pruning. The<br>
subtree with the largest cost complexity that is smaller than<br>
``ccp_alpha`` will be chosen. By default, no pruning is performed. See<br>
:ref:`minimal_cost_complexity_pruning` for details. See<br>
:ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`<br>
for an example of such pruning.<br>
<br>
.. versionadded:: 0.22</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.tree.DecisionTreeClassifier.html#:~:text=monotonic_cst,-array-like%20of%20int%20of%20shape%20%28n_features%29%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">monotonic_cst <span class="param-doc-description">monotonic_cst: array-like of int of shape (n_features), default=None<br>
<br>
Indicates the monotonicity constraint to enforce on each feature.<br>
- 1: monotonic increase<br>
- 0: no constraint<br>
- -1: monotonic decrease<br>
<br>
If monotonic_cst is None, no constraints are applied.<br>
<br>
Monotonicity constraints are not supported for:<br>
- multiclass classifications (i.e. when `n_classes &gt; 2`),<br>
- multioutput classifications (i.e. when `n_outputs_ &gt; 1`),<br>
- classifications trained on data with missing values.<br>
<br>
The constraints hold over the probability of the positive class.<br>
<br>
Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.<br>
<br>
.. versionadded:: 1.4</monotonic_cst_gbdt></span></a></td>
<td class="value">None</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div></div></div><script>function copyToClipboard(text, element) {
    // Get the parameter prefix from the closest toggleable content
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;

    const originalStyle = element.style;
    const computedStyle = window.getComputedStyle(element);
    const originalWidth = computedStyle.width;
    const originalHTML = element.innerHTML.replace('Copied!', '');

    navigator.clipboard.writeText(fullParamName)
        .then(() => {
            element.style.width = originalWidth;
            element.style.color = 'green';
            element.innerHTML = "Copied!";

            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        })
        .catch(err => {
            console.error('Failed to copy:', err);
            element.style.color = 'red';
            element.innerHTML = "Failed!";
            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        });
    return false;
}

document.querySelectorAll('.copy-paste-icon').forEach(function(element) {
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const paramName = element.parentElement.nextElementSibling
        .textContent.trim().split(' ')[0];
    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;

    element.setAttribute('title', fullParamName);
});


/**
 * Adapted from Skrub
 * https://github.com/skrub-data/skrub/blob/403466d1d5d4dc76a7ef569b3f8228db59a31dc3/skrub/_reporting/_data/templates/report.js#L789
 * @returns "light" or "dark"
 */
function detectTheme(element) {
    const body = document.querySelector('body');

    // Check VSCode theme
    const themeKindAttr = body.getAttribute('data-vscode-theme-kind');
    const themeNameAttr = body.getAttribute('data-vscode-theme-name');

    if (themeKindAttr && themeNameAttr) {
        const themeKind = themeKindAttr.toLowerCase();
        const themeName = themeNameAttr.toLowerCase();

        if (themeKind.includes("dark") || themeName.includes("dark")) {
            return "dark";
        }
        if (themeKind.includes("light") || themeName.includes("light")) {
            return "light";
        }
    }

    // Check Jupyter theme
    if (body.getAttribute('data-jp-theme-light') === 'false') {
        return 'dark';
    } else if (body.getAttribute('data-jp-theme-light') === 'true') {
        return 'light';
    }

    // Guess based on a parent element's color
    const color = window.getComputedStyle(element.parentNode, null).getPropertyValue('color');
    const match = color.match(/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)\s*$/i);
    if (match) {
        const [r, g, b] = [
            parseFloat(match[1]),
            parseFloat(match[2]),
            parseFloat(match[3])
        ];

        // https://en.wikipedia.org/wiki/HSL_and_HSV#Lightness
        const luma = 0.299 * r + 0.587 * g + 0.114 * b;

        if (luma > 180) {
            // If the text is very bright we have a dark theme
            return 'dark';
        }
        if (luma < 75) {
            // If the text is very dark we have a light theme
            return 'light';
        }
        // Otherwise fall back to the next heuristic.
    }

    // Fallback to system preference
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}


function forceTheme(elementId) {
    const estimatorElement = document.querySelector(`#${elementId}`);
    if (estimatorElement === null) {
        console.error(`Element with id ${elementId} not found.`);
    } else {
        const theme = detectTheme(estimatorElement);
        estimatorElement.classList.add(theme);
    }
}

forceTheme('sk-container-id-1');</script>
</div>
</div>
<p><code>sklearn</code> provide a way to automatically generate the tree view of the decision tree. The code is as follows.</p>
<div id="1abed0bb" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> plot_tree</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">3</span>, <span class="dv">3</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plot_tree(clf, filled<span class="op">=</span><span class="va">True</span>, impurity<span class="op">=</span><span class="va">True</span>, node_ids<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>[Text(0.5, 0.9166666666666666, 'node #0\nx[1] &lt;= 0.8\ngini = 0.667\nsamples = 150\nvalue = [50, 50, 50]'),
 Text(0.4090909090909091, 0.75, 'node #1\ngini = 0.0\nsamples = 50\nvalue = [50, 0, 0]'),
 Text(0.4545454545454546, 0.8333333333333333, 'True  '),
 Text(0.5909090909090909, 0.75, 'node #2\nx[1] &lt;= 1.75\ngini = 0.5\nsamples = 100\nvalue = [0, 50, 50]'),
 Text(0.5454545454545454, 0.8333333333333333, '  False'),
 Text(0.36363636363636365, 0.5833333333333334, 'node #3\nx[0] &lt;= 4.95\ngini = 0.168\nsamples = 54\nvalue = [0, 49, 5]'),
 Text(0.18181818181818182, 0.4166666666666667, 'node #4\nx[1] &lt;= 1.65\ngini = 0.041\nsamples = 48\nvalue = [0, 47, 1]'),
 Text(0.09090909090909091, 0.25, 'node #5\ngini = 0.0\nsamples = 47\nvalue = [0, 47, 0]'),
 Text(0.2727272727272727, 0.25, 'node #6\ngini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.5454545454545454, 0.4166666666666667, 'node #7\nx[1] &lt;= 1.55\ngini = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(0.45454545454545453, 0.25, 'node #8\ngini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.6363636363636364, 0.25, 'node #9\nx[0] &lt;= 5.45\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.5454545454545454, 0.08333333333333333, 'node #10\ngini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.7272727272727273, 0.08333333333333333, 'node #11\ngini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.8181818181818182, 0.5833333333333334, 'node #12\nx[0] &lt;= 4.85\ngini = 0.043\nsamples = 46\nvalue = [0, 1, 45]'),
 Text(0.7272727272727273, 0.4166666666666667, 'node #13\ngini = 0.444\nsamples = 3\nvalue = [0, 1, 2]'),
 Text(0.9090909090909091, 0.4166666666666667, 'node #14\ngini = 0.0\nsamples = 43\nvalue = [0, 0, 43]')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-14-output-2.png" width="505" height="502" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<details>
<summary>
Visualize decision boundary is optional.
</summary>
<p>Similar to k-NN, we may use <code>sklearn.inspection.DecisionBoundaryDisplay</code> to visualize the decision boundary of this decision tree.</p>
<div id="fc7a28d0" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.inspection <span class="im">import</span> DecisionBoundaryDisplay</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>DecisionBoundaryDisplay.from_estimator(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    clf,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    X,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">'coolwarm'</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    response_method<span class="op">=</span><span class="st">"predict"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span>iris.feature_names[<span class="dv">0</span>],</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    ylabel<span class="op">=</span>iris.feature_names[<span class="dv">1</span>],</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the training points</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>plt.scatter(X[:, <span class="dv">0</span>], X[:, <span class="dv">1</span>], c<span class="op">=</span>y, s<span class="op">=</span><span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-15-output-1.png" width="600" height="434" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details>
</section>
<section id="tuning-hyperparameters-1" class="level3" data-number="7.10.3">
<h3 data-number="7.10.3" class="anchored" data-anchor-id="tuning-hyperparameters-1"><span class="header-section-number">7.10.3</span> Tuning hyperparameters</h3>
<p>Building a decision tree is the same as splitting the training dataset. If we are alllowed to keep splitting it, it is possible to get to a case that each end node is pure: the Gini impurity is 0. This means two things:</p>
<ol type="1">
<li>The tree learns too many (unnecessary) detailed info from the training set which might not be applied to the test set. This is called <em>overfitting</em>. We should prevent a model from overfitting.</li>
<li>We could use the number of split to indicate the progress of the learning.</li>
</ol>
<p>In other words, the finer the splits are, the further the learning is. We need to consider some early stop conditions to prevent the model from overfitting.</p>
<p>Some possible early stop conditions:</p>
<ul>
<li><code>max_depth</code>: The max depth of the tree. The default is <code>none</code> which means no limits.</li>
<li><code>min_samples_split</code>: The minimum number of samples required to split an internal node. The default is 2 which means that we will split a node with as few as 2 elements if needed.</li>
<li><code>min_samples_leaf</code>: The minimum number of samples required to be at a leaf node. The default is 1 which means that we will still split the node even if one subset only contains 1 element.</li>
</ul>
<p>If we don’t set them (which means that we use the default setting), the dataset will be split untill all subsets are pure.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 7.4 (ALMOST all end nodes are pure)</strong></span> In this example, we let the tree grow as further as possible. It only stops when (almost) all end nodes are pure, even if the end nodes only contain ONE element (like #6 and #11).</p>
<div id="5c4458f7" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">40</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>clf.fit(X, y)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">3</span>, <span class="dv">3</span>), dpi<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plot_tree(clf, filled<span class="op">=</span><span class="va">True</span>, impurity<span class="op">=</span><span class="va">True</span>, node_ids<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>[Text(0.5, 0.9166666666666666, 'node #0\nx[1] &lt;= 0.8\ngini = 0.667\nsamples = 150\nvalue = [50, 50, 50]'),
 Text(0.4090909090909091, 0.75, 'node #1\ngini = 0.0\nsamples = 50\nvalue = [50, 0, 0]'),
 Text(0.4545454545454546, 0.8333333333333333, 'True  '),
 Text(0.5909090909090909, 0.75, 'node #2\nx[1] &lt;= 1.75\ngini = 0.5\nsamples = 100\nvalue = [0, 50, 50]'),
 Text(0.5454545454545454, 0.8333333333333333, '  False'),
 Text(0.36363636363636365, 0.5833333333333334, 'node #3\nx[0] &lt;= 4.95\ngini = 0.168\nsamples = 54\nvalue = [0, 49, 5]'),
 Text(0.18181818181818182, 0.4166666666666667, 'node #4\nx[1] &lt;= 1.65\ngini = 0.041\nsamples = 48\nvalue = [0, 47, 1]'),
 Text(0.09090909090909091, 0.25, 'node #5\ngini = 0.0\nsamples = 47\nvalue = [0, 47, 0]'),
 Text(0.2727272727272727, 0.25, 'node #6\ngini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.5454545454545454, 0.4166666666666667, 'node #7\nx[1] &lt;= 1.55\ngini = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(0.45454545454545453, 0.25, 'node #8\ngini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.6363636363636364, 0.25, 'node #9\nx[0] &lt;= 5.45\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.5454545454545454, 0.08333333333333333, 'node #10\ngini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.7272727272727273, 0.08333333333333333, 'node #11\ngini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.8181818181818182, 0.5833333333333334, 'node #12\nx[0] &lt;= 4.85\ngini = 0.043\nsamples = 46\nvalue = [0, 1, 45]'),
 Text(0.7272727272727273, 0.4166666666666667, 'node #13\ngini = 0.444\nsamples = 3\nvalue = [0, 1, 2]'),
 Text(0.9090909090909091, 0.4166666666666667, 'node #14\ngini = 0.0\nsamples = 43\nvalue = [0, 0, 43]')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-16-output-2.png" width="505" height="502" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In this example there is one exception. #13 node is not pure. The reason is as follows.</p>
<div id="edab86d1" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>X[(X[:, <span class="dv">0</span>]<span class="op">&gt;</span><span class="fl">0.8</span>) <span class="op">&amp;</span> (X[:, <span class="dv">1</span>] <span class="op">&gt;</span><span class="fl">1.75</span>) <span class="op">&amp;</span> (X[:, <span class="dv">0</span>]<span class="op">&lt;=</span><span class="fl">4.85</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>array([[4.8, 1.8],
       [4.8, 1.8],
       [4.8, 1.8]])</code></pre>
</div>
</div>
<p>All the data points in this node has the same feature while their labels are different. They cannot be split further purely based on features.</p>
</div>
<p>Therefore we could treat these hyperparameters as an indicator about how far the dataset is split. The further the dataset is split, the further the learning goes, the more details are learned. Since we don’t want the model to be overfitting, we don’t want to split the dataset that far. In this case, we could use the learning curve to help us make the decision.</p>
<p>In this example, let us choose <code>min_samples_leaf</code> as the indicator. When <code>min_samples_leaf</code> is big, the learning just starts. When <code>min_samples_leaf=1</code>, we reach the far most side of learning. We will see how the training and testing accuracy changes along the learning process.</p>
<div id="307bbaad" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.15</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>num_leaf <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">100</span>))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>train_acc <span class="op">=</span> []</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>test_acc <span class="op">=</span> []</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> num_leaf:</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>, min_samples_leaf<span class="op">=</span>i)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    clf.fit(X_train, y_train)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    train_acc.append(clf.score(X_train, y_train))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    test_acc.append(clf.score(X_test, y_test))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>plt.plot(num_leaf, train_acc, label<span class="op">=</span><span class="st">'training'</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>plt.plot(num_leaf, test_acc, label<span class="op">=</span><span class="st">'testing'</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>plt.gca().set_xlim((<span class="bu">max</span>(num_leaf)<span class="op">+</span><span class="dv">1</span>, <span class="bu">min</span>(num_leaf)<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-18-output-1.png" width="575" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From this plot, the accuracy has a big jump at <code>min_sample_leaf=41</code>. So we could choose this to be our hyperparameter.</p>
</section>
<section id="pruning-1" class="level3" data-number="7.10.4">
<h3 data-number="7.10.4" class="anchored" data-anchor-id="pruning-1"><span class="header-section-number">7.10.4</span> Pruning</h3>
<p>Other than tuning hyperparameters, we also want to prune our tree in order to reduce overfitting further. The pruning algorithm introduced together with CART is called <strong>Minimal-Cost-Complexity Pruning</strong> (MCCP).</p>
<p>The idea is to use the cost-complexity measure to replace Gini impurity to grow the tree. The cost-complexity measure is gotten by adding the total number of end nodes with the coefficent <code>ccp_alpha</code> to the Gini impurity. The parameter <code>ccp_alpha&gt;=0</code> is known as the <strong>complexity parameter</strong>, and it can help the tree to self-balance the number of end nodes and the Gini impurity.</p>
<p>In <code>sklearn</code>, we use <code>cost_complexity_pruning_path</code> to help us find the effective alphas and the corresponding impurities.</p>
<div id="fa0392c0" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ccp_path <span class="op">=</span> clf.cost_complexity_pruning_path(X_train, y_train)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>ccp_alphas, impurities <span class="op">=</span> ccp_path.ccp_alphas, ccp_path.impurities</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The list <code>ccp_alphas</code> contains all important <code>ccp_alpha</code>s. We could train a model for each of them. We could use the argument <code>ccp_alpha</code> to control the value when initialize the model. After we train all these tree models for each effective <code>ccp_alpha</code>, we evaluate the model and record the results.</p>
<div id="66450d6b" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>clfs <span class="op">=</span> []</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ccp_alpha <span class="kw">in</span> ccp_alphas:</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    clf <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>, ccp_alpha<span class="op">=</span>ccp_alpha)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    clf.fit(X_train, y_train)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    clfs.append(clf)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>node_counts <span class="op">=</span> [clf.tree_.node_count <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>depth <span class="op">=</span> [clf.tree_.max_depth <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>train_acc <span class="op">=</span> [clf.score(X_train, y_train) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>test_acc <span class="op">=</span> [clf.score(X_test, y_test) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We would like to visualize these info.</p>
<div id="bd7f4b6d" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(ccp_alphas, node_counts, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">"number of nodes"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(ccp_alphas, depth, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">"depth of tree"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].plot(ccp_alphas, train_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].plot(ccp_alphas, test_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'test'</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_ylabel(<span class="st">"accuracy"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].legend()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-21-output-1.png" width="597" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Based on the plot, it seems that the fourth dot 0.01534424 is a good fit. So this is the complexity parameter we are going to use.</p>
<details>
<summary>
We could combine all the code above into a function.
</summary>
<div id="4d1d6b6f" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.base <span class="im">import</span> clone</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> eval_ccp_alphas(clf, X, y):</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    ccp_path <span class="op">=</span> clf.cost_complexity_pruning_path(X, y)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    ccp_alphas, impurities <span class="op">=</span> ccp_path.ccp_alphas, ccp_path.impurities</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    clfs <span class="op">=</span> []</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ccp_alpha <span class="kw">in</span> ccp_alphas:</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>        clf_tmp <span class="op">=</span> clone(clf)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>        clf_tmp.set_params(ccp_alpha<span class="op">=</span>ccp_alpha)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>        clf_tmp.fit(X, y)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>        clfs.append(clf_tmp)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    node_counts <span class="op">=</span> [clf.tree_.node_count <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    depth <span class="op">=</span> [clf.tree_.max_depth <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    train_acc <span class="op">=</span> [clf.score(X_train, y_train) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    test_acc <span class="op">=</span> [clf.score(X_test, y_test) <span class="cf">for</span> clf <span class="kw">in</span> clfs]</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].plot(ccp_alphas, node_counts, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].set_ylabel(<span class="st">"number of nodes"</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].plot(ccp_alphas, depth, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].set_ylabel(<span class="st">"depth of tree"</span>)</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].plot(ccp_alphas, train_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].plot(ccp_alphas, test_acc, marker<span class="op">=</span><span class="st">"o"</span>, drawstyle<span class="op">=</span><span class="st">"steps-post"</span>, label<span class="op">=</span><span class="st">'test'</span>)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].set_xlabel(<span class="st">"alpha"</span>)</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].set_ylabel(<span class="st">"accuracy"</span>)</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">2</span>].legend()</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ccp_alphas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="5902b03f" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>eval_ccp_alphas(DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>), X_train, y_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>array([0.        , 0.00485564, 0.01049869, 0.01534424, 0.03364964,
       0.24888323, 0.33214852])</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tree_files/figure-html/cell-23-output-2.png" width="597" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details>
</section>
</section>
</section>
<section id="regression-trees-1" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Regression Trees</h1>
<section id="why-trees" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="why-trees"><span class="header-section-number">8.1</span> 1. Why trees?</h2>
</section>
<section id="tree-complexity" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="tree-complexity"><span class="header-section-number">8.2</span> 10. Tree complexity</h2>
<p>A fully grown tree can fit the training data very closely, but it often overfits.</p>
<p>Important complexity controls include:</p>
<ul>
<li><code>max_depth</code>: maximum tree depth</li>
<li><code>min_samples_split</code>: minimum number of observations required to split a node</li>
<li><code>min_samples_leaf</code>: minimum number of observations in a terminal node</li>
<li><code>max_leaf_nodes</code>: maximum number of leaves</li>
<li><code>ccp_alpha</code>: cost-complexity pruning parameter</li>
</ul>
<p>Small trees are more stable but may underfit.</p>
<p>Large trees are flexible but may overfit.</p>
<p>The main tuning problem is to choose the right tree size.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Rule of thumb
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tree size controls the bias-variance tradeoff.</p>
<p>A larger tree is not automatically better, even if it has smaller training error.</p>
</div>
</div>
</section>
<section id="stopping-rules" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="stopping-rules"><span class="header-section-number">8.3</span> 11. Stopping rules</h2>
<p>Stopping rules decide when the recursive splitting process should stop.</p>
<p>Common stopping rules include:</p>
<ul>
<li>stop when the node is too small</li>
<li>stop when the tree reaches a maximum depth</li>
<li>stop when the improvement in RSS is too small</li>
<li>stop when a leaf-size constraint would be violated</li>
</ul>
<p>These rules are called pre-pruning because they stop the tree before it becomes too large.</p>
<p>Pre-pruning is simple, but it can be too greedy. A split that looks weak now might allow useful splits later.</p>
<p>For this reason, another common strategy is:</p>
<ol type="1">
<li>Grow a large tree.</li>
<li>Prune it back.</li>
<li>Use validation or cross-validation to choose the final size.</li>
</ol>
</section>
<section id="cost-complexity-pruning" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="cost-complexity-pruning"><span class="header-section-number">8.4</span> 12. Cost-complexity pruning</h2>
<p>Let <span class="math inline">\(T\)</span> be a subtree, and let <span class="math inline">\(|T|\)</span> be the number of terminal nodes.</p>
<p>For regression, the cost-complexity criterion is <span class="math display">\[
C_\alpha(T)
=
\sum_{m=1}^{|T|}
\sum_{x_i\in R_m}
(y_i-\bar y_{R_m})^2
+
\alpha |T|.
\]</span></p>
<p>The first term measures training error.</p>
<p>The second term penalizes tree complexity.</p>
<ul>
<li><span class="math inline">\(\alpha=0\)</span>: prefer a large tree</li>
<li>larger <span class="math inline">\(\alpha\)</span>: prefer a smaller tree</li>
</ul>
<p>This has the same structure as regularized regression: <span class="math display">\[
\text{loss}+\text{penalty}.
\]</span></p>
<p>The tuning parameter <span class="math inline">\(\alpha\)</span> controls how expensive it is to add another leaf.</p>
<p>If a split reduces RSS by only a small amount, it will not be worth keeping when <span class="math inline">\(\alpha\)</span> is large.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of <span class="math inline">\(\alpha\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The pruning parameter <span class="math inline">\(\alpha\)</span> controls the tradeoff between fit and complexity.</p>
<p>It plays the same conceptual role as a tuning parameter in ridge or lasso.</p>
</div>
</div>
</section>
<section id="bias-variance-tradeoff" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="bias-variance-tradeoff"><span class="header-section-number">8.5</span> 13. Bias-variance tradeoff</h2>
<p>Regression trees have a clear bias-variance tradeoff.</p>
<p>A shallow tree:</p>
<ul>
<li>has fewer leaves</li>
<li>gives smoother, more stable predictions</li>
<li>has higher bias</li>
<li>has lower variance</li>
</ul>
<p>A deep tree:</p>
<ul>
<li>has many leaves</li>
<li>adapts strongly to the training data</li>
<li>has lower bias</li>
<li>has higher variance</li>
</ul>
<p>This is one reason a single tree is usually not the final model for high-performance prediction.</p>
<p>Random forests and boosting improve on trees by combining many trees.</p>
<p>The connection is:</p>
<ul>
<li>bagging and random forests mainly reduce variance</li>
<li>boosting often reduces bias by fitting trees sequentially</li>
</ul>
</section>
<section id="variable-importance" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="variable-importance"><span class="header-section-number">8.6</span> 14. Variable importance</h2>
<p>Trees can be used to measure variable importance.</p>
<p>A common idea is to add up how much each variable reduces impurity across all splits.</p>
<p>For regression, impurity reduction means reduction in RSS or variance.</p>
<p>If a variable is used often near the top of the tree and creates large reductions in RSS, it receives high importance.</p>
<p>This is useful, but it should be interpreted carefully.</p>
<p>Variable importance can be affected by:</p>
<ul>
<li>correlated predictors</li>
<li>variables with many possible split points</li>
<li>instability of a single tree</li>
<li>preprocessing choices</li>
</ul>
<p>For more reliable importance measures, ensembles and permutation importance are often better.</p>
</section>
<section id="strengths" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="strengths"><span class="header-section-number">8.7</span> 15. Strengths</h2>
<p>Regression trees are useful because they:</p>
<ul>
<li>are easy to interpret</li>
<li>automatically handle nonlinear relationships</li>
<li>automatically capture interactions</li>
<li>do not require feature scaling</li>
<li>can handle mixed variable types</li>
<li>are easy to visualize</li>
<li>are robust to monotone transformations of predictors</li>
<li>provide a natural basis for random forests and boosting</li>
</ul>
<p>The biggest strength is interpretability.</p>
<p>A tree can often be explained as a sequence of simple rules.</p>
</section>
<section id="weaknesses" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="weaknesses"><span class="header-section-number">8.8</span> 16. Weaknesses</h2>
<p>A single regression tree also has important limitations:</p>
<ul>
<li>prediction is piecewise constant</li>
<li>fitted function is not smooth</li>
<li>small changes in data can change the tree</li>
<li>high variance</li>
<li>often weaker predictive performance than ensembles</li>
<li>poor extrapolation outside the training range</li>
<li>axis-aligned splits can be inefficient for diagonal patterns</li>
</ul>
<p>Poor extrapolation is especially important.</p>
<p>If a test point has a predictor value outside the training range, a tree still predicts using the average of some training leaf. It does not continue a linear trend beyond the observed data.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A single tree is usually better as an interpretable model or as a building block.</p>
<p>For prediction, ensembles of trees are usually much stronger.</p>
</div>
</div>
</section>
<section id="minimal-python-example" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="minimal-python-example"><span class="header-section-number">8.9</span> 17. Minimal Python example</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV, train_test_split</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeRegressor</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    X,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    y,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    test_size<span class="op">=</span><span class="fl">0.3</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeRegressor(random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"max_depth"</span>: [<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="va">None</span>],</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min_samples_leaf"</span>: [<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>],</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ccp_alpha"</span>: [<span class="fl">0.0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.1</span>],</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> GridSearchCV(</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    tree,</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    param_grid<span class="op">=</span>param_grid,</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    cv<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>    scoring<span class="op">=</span><span class="st">"neg_mean_squared_error"</span>,</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>grid.fit(X_train, y_train)</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>best_tree <span class="op">=</span> grid.best_estimator_</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> best_tree.predict(X_test)</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>test_mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grid.best_params_)</span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(test_mse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The important point is that tuning should be done using validation data or cross-validation, not by choosing the tree with the smallest training error.</p>
</section>
<section id="cost-complexity-pruning-path-in-sklearn" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="cost-complexity-pruning-path-in-sklearn"><span class="header-section-number">8.10</span> 18. Cost-complexity pruning path in sklearn</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeRegressor</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeRegressor(random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> tree.cost_complexity_pruning_path(X_train, y_train)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>ccp_alphas <span class="op">=</span> path.ccp_alphas</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>cv_mse <span class="op">=</span> []</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> alpha <span class="kw">in</span> ccp_alphas:</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> DecisionTreeRegressor(</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        random_state<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>        ccp_alpha<span class="op">=</span>alpha,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> cross_val_score(</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>        model,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>        X_train,</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>        y_train,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>        cv<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>        scoring<span class="op">=</span><span class="st">"neg_mean_squared_error"</span>,</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    cv_mse.append(<span class="op">-</span>scores.mean())</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>best_alpha <span class="op">=</span> ccp_alphas[np.argmin(cv_mse)]</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>pruned_tree <span class="op">=</span> DecisionTreeRegressor(</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>    ccp_alpha<span class="op">=</span>best_alpha,</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>pruned_tree.fit(X_train, y_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The pruning path gives a sequence of candidate values for <code>ccp_alpha</code>.</p>
<p>Cross-validation chooses which subtree gives the best prediction error.</p>
</section>
<section id="summary" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.11</span> 19. Summary</h2>
<p>A regression tree is an adaptive partitioning method.</p>
<p>Its fitted model is <span class="math display">\[
\hat f(x)
=
\sum_{m=1}^M
\bar y_{R_m} I(x\in R_m).
\]</span></p>
<p>The algorithm chooses splits to reduce within-node variation, usually measured by RSS or variance.</p>
<p>The fitted function is piecewise constant.</p>
<p>The main tuning problem is controlling tree size.</p>
<p>A single tree is interpretable, flexible, and useful for discovering structure, but it is often unstable.</p>
<p>This motivates ensemble methods such as bagging, random forests, and boosting.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../contents/2/lda.html" class="pagination-link" aria-label="LDA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">LDA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../contents/3/ensemble.html" class="pagination-link" aria-label="Ensemble Methods">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ensemble Methods</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>