project:
  type: book
  output-dir: docs
  resources:
    - fonts/

number-sections: true
# top-level-division: part
toc-depth: 3
number-depth: 4
bibliography: reference.bib
csl: "ims.csl"
 
crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)
 
execute:
  freeze: auto

knitr:
  opts_chunk:
    # comment: "#>"
    collapse: false


 
book:
  title: "Statistical Learning"
  author: "Weijia Jia"
  date: last-modified
  chapters: 
    - index.qmd
    - part: "Linear models"
      chapters:
      - contents/1/basic.qmd
      - contents/1/lr.qmd
      - contents/1/shrinkage.qmd      
      - contents/1/dr.qmd
      # - contents/1/glm.qmd
      # - contents/1/gam.qmd
    - part: "Classification"
      chapters: 
      - contents/2/logistic.qmd
      - contents/2/lda.qmd
      - contents/2/decisioneval.qmd
    - part: "Tree Based Methods"
      chapters: 
      - contents/3/tree.qmd
      - contents/3/rf.qmd
      - contents/3/boost.qmd
    - part: "Distance Based Methods"
      chapters:
      - contents/4/knn.qmd
      - contents/4/kernel.qmd
      - contents/4/cluster.qmd
    #   - contents/2/svm.qmd
    #   - contents/2/lda.qmd
    #   - contents/2/tree.qmd
    #   - contents/2/ensemble.qmd
    # - part: "Unsupervised Learning"
    #   chapters:
    #   - contents/3/cluster.qmd
      # - contents/3/rkhs.qmd
    #   - contents/3/cat.qmd
    #   # - contents/3/rcode2.qmd
    #   - contents/3/project2.qmd
    # - part: "Building models"
    #   chapters:
    #   - contents/4/vs.qmd
      # - contents/4/ra.qmd
  appendices:
    - contents/app/ide.qmd
    - contents/app/venv.qmd
    # - contents/app/r.qmd
  #   - contents/app/hypo.qmd
  sidebar:
    style: "docked"
    # pinned: true
    # align: center
    # border: true
    search: true
    collapse-level: 1
    # alignment: "center"
  # navbar: 
  #   background: primary
  #   search: true
  #   left: 
  #     - text: "Home"
  #       menu: 
  #       - contents/index.qmd
  page-navigation: true
  bread-crumbs: false
  search: true
  reader-mode: true
   

format:
  html:
    toc: true
    toc-depth: 3
    theme:
      light:
        - styles/light.scss
      dark:
        - styles/light.scss
        - styles/dark.scss
    css:
      - styles/fonts.css
      - styles/blocks.css
    mermaid:
      theme: default
    mainfont: Noto Serif
    sansfont: Noto Sans
    # mainfont: Libertinus Serif
    # sansfont: Libertinus Sans

    mathfont: Libertinus Math
    monofont: JetBrains Mono
    # # monofont: Latin Modern Mono
    monofontoptions:
      - Scale=0.95

    fontsize: 12pt
    # linestretch: 1.1

    code-annotations: select
    code-overflow: scroll
    code-block-bg: true
    code-block-border-left: true #"#31BAE9"
    # code-line-numbers: true
    highlight-style: atom-one
    page-layout: article

# filters:
#   - pseudocode

# pseudocode:
#   caption-prefix: "Algorithm"
#   reference-prefix: "Algorithm"
#   caption-number: true
