project:
  type: default



lang: en
format: 
  pdf:
    pdf-standard: ua-2
    pdf-engine: lualatex
    template-partials:
      - doc-class.tex
    include-in-header:
      - math.tex
      - pdfheader.tex
    mainfont: Libertinus Serif
    sansfont: Libertinus Sans
    monofont: Latin Modern Mono
    monofontoptions:
      - Scale=0.95
    mathfont: Libertinus Math
    highlight-style: arrow
  # typst:
  #   toc: false
  #   section-numbering: 1.1.1
  #   columns: 1
  #   pdf-standard: ua-2
  #   mainfont: "libertinus serif"  
crossref:
  chapters: false