{
  "hash": "3cebc70bbf01741afbacb9e3c6a6f3c7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\njupyter: stats\n---\n\n<!-- {{< include ../t/math.qmd >}} -->\n\n\n\n# Clustering {#sec-clustering}\n\nClustering is an unsupervised learning problem. We observe only a feature matrix $X\\in\\mathbb R^{n\\times p}$ and seek to partition the observations into groups whose members are similar. Unlike classification, there are no training labels that define the target categories.\n\nClustering is commonly used to explore latent subpopulations, summarize a large dataset with a small number of groups or prototypes, organize observations for visualization, and generate hypotheses for later scientific analysis.\n\n::: {.callout-caution}\n## A cluster is not automatically a real category\n\nA clustering algorithm produces cluster assignments according to its objective and tuning choices. The result may reflect meaningful structure, but it may also reflect feature scaling, outliers, an unsuitable dissimilarity measure, or a forced choice of the number of clusters. Interpretation is part of the analysis.\n:::\n\n<!-- ## Overview of the Main Approaches -->\n\nClustering methods differ in their definition of a group. In the notes we focuses on three major direct clustering paradigms, represented by one typical method from each:\n\n| Family | Typical method | What defines a cluster? |\n|---|---|---|\n| Centroid-based | K-means | observations close to the same center |\n| Hierarchical | agglomerative hierarchical clustering | observations joined through a sequence of merges |\n| Density-based | DBSCAN | observations connected through dense regions |\n\nMany other clustering approaches exist, including graph-based and representation-based methods. The three paradigms here are emphasized because they give distinct direct definitions of what constitutes a cluster. We use one representative algorithm from each paradigm to illustrate the main ideas.\n\n\n\n\n\n::: {.callout-note}\n\n## Distance, Similarity, and Scaling\n\nMost clustering methods require a notion of similarity or dissimilarity. For numerical data, a common choice is Euclidean distance: $d(x_i,x_j)=\\norm{x_i-x_j}_2=\\sqrt{\\sum_{\\ell=1}^p(x_{i\\ell}-x_{j\\ell})^2}$.\n\nThe distance defines what the algorithm means by *similar*. Changing the features, their scales, or the dissimilarity measure changes the clustering problem. Features with larger numerical ranges can dominate distance calculations, so standardization is often useful when feature scales are not directly comparable.\n\nEuclidean distance is not the only option. Manhattan distance, cosine similarity, or a domain-specific measure may be more appropriate depending on the structure one hopes to discover.\n:::\n\n::: {.callout-note}\n\n## Scaling is a modeling decision\n\nStandardize when numerical scales are arbitrary or incomparable. Do not standardize automatically when the original magnitudes are scientifically meaningful, such as comparable pixel intensities or measurements already expressed on a common scale.\n:::\n\n\n\n\n\n\n\n## Evaluating a Clustering\n\nEvaluating clustering differs from evaluating supervised learning. In classification or regression, the response variable defines what a correct prediction means, and performance can be measured on held-out labeled data. In clustering, group membership is not observed during fitting. The algorithm produces cluster assignments, but several different assignments may be reasonable for the same dataset depending on the features, scaling, distance, and scientific question.\n\nFor this reason, clustering evaluation usually separates two questions:\n\n- Are the fitted clusters geometrically coherent in the observed feature space?\n- If reference labels are available, how well do the cluster assignments agree with those external labels?\n\nAlthough some evaluation measures are commonly associated with particular clustering methods, the focus here is on the metrics themselves; the corresponding algorithms are discussed in later sections.\n\n\n### WCSS (or Inertia)\n\nInternal clustering metrics use only the observations and their cluster assignments. They can compare values of $K$, initializations, or methods, but only when the observations, features, scaling, and distance are held fixed. They measure geometric properties of the fitted clustering, not whether the clusters correspond to meaningful external categories.\n\nTwo common internal metrics are WCSS and the silhouette value.\n\nThe examples below use a small hypothetical dataset to illustrate the mechanics of the evaluation. We first visualize one set of cluster assignments.\n\n<!-- fmt: off -->\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nX_eval = np.array([\n    [0.0, 0.1],\n    [0.2, 0.0],\n    [0.1, 0.3],\n    [4.0, 4.1],\n    [4.2, 3.9],\n    [3.8, 4.0],\n    [8.0, 0.0],\n    [8.2, 0.2],\n    [7.9, -0.1],\n    [8.1, 0.1],\n])\n\ncluster_eval = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])\n\nplt.scatter(X_eval[:, 0], X_eval[:, 1], c=cluster_eval)\nplt.gcf().set_size_inches(5, 3)\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-2-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n<!-- fmt: on -->\n\nThe within-cluster sum of squares (WCSS) measures the total squared distance from each observation to the center of its assigned cluster. If $\\mu_k$ is the center of cluster $C_k$, then\n\n$$\n\\operatorname{WCSS}\n=\n\\sum_{k=1}^K\n\\sum_{i\\in C_k}\n\\norm{x_i-\\mu_k}_2^2.\n$$\n\nWCSS can be computed once cluster assignments and centers are specified. For arbitrary cluster labels, a natural choice is to set each center to the mean of its assigned observations. If only centers are given, as in the K-means assignment step, each observation is first assigned to its nearest center and WCSS is then computed from those assignments.\n\nFor K-means, WCSS is both the fitting objective and an internal measure of cluster compactness. It plays a role similar to the residual sum of squares (RSS) in regression: smaller values indicate that observations are closer to their fitted centers.\n\nWCSS can be computed for any assignment of observations to clusters using any methods. However, it is most naturally associated with K-means because K-means explicitly minimizes WCSS during fitting. For clustering methods designed to detect non-spherical or density-based structures, WCSS may not provide a meaningful assessment of clustering quality.\n\nIn `sklearn`, WCSS is also called inertia and is stored as `.inertia_` on a fitted `KMeans` object. This is the WCSS for the fitted centers, specifically the best solution among the initializations tried. There is no general `sklearn` API for computing WCSS from arbitrary centers or labels.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nfrom sklearn.cluster import KMeans\n\nkmeans_eval = KMeans(n_clusters=3, n_init=20, random_state=1)\nkmeans_eval.fit(X_eval)\nkmeans_eval.inertia_\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n0.26666666666666655\n```\n:::\n:::\n\n\n<details>\n<summary><strong>Click to expand.</strong></summary>\n\nFor this example, the three fitted groups have centers\n\n$$\n\\mu_0\n=\n\\frac{(0.0,0.1)+(0.2,0.0)+(0.1,0.3)}{3}\n=\n\\left(0.1,\\frac{2}{15}\\right),\n$$\n\n$$\n\\mu_1\n=\n\\frac{(4.0,4.1)+(4.2,3.9)+(3.8,4.0)}{3}\n=\n(4.0,4.0),\n$$\n\n$$\n\\mu_2\n=\n\\frac{(8.0,0.0)+(8.2,0.2)+(7.9,-0.1)+(8.1,0.1)}{4}\n=\n(8.05,0.05).\n$$\n\nPlugging these centers into the WCSS formula gives\n\n$$\n\\begin{aligned}\n\\operatorname{WCSS}_0\n=&\n\\left\\|(0.0,0.1)-\\left(0.1,\\frac{2}{15}\\right)\\right\\|^2\n+\\left\\|(0.2,0.0)-\\left(0.1,\\frac{2}{15}\\right)\\right\\|^2\n+\\left\\|(0.1,0.3)-\\left(0.1,\\frac{2}{15}\\right)\\right\\|^2\\\\\n=&\n\\frac{1}{15},\\\\\n\\operatorname{WCSS}_1\n=&\n\\|(4.0,4.1)-(4.0,4.0)\\|^2\n+\\|(4.2,3.9)-(4.0,4.0)\\|^2\n+\\|(3.8,4.0)-(4.0,4.0)\\|^2\\\\\n=&0.10,\\\\\n\\operatorname{WCSS}_2\n=&\n\\|(8.0,0.0)-(8.05,0.05)\\|^2\n+\\|(8.2,0.2)-(8.05,0.05)\\|^2+\\|(7.9,-0.1)-(8.05,0.05)\\|^2\n+\\|(8.1,0.1)-(8.05,0.05)\\|^2\\\\\n=&0.10.\n\\end{aligned}\n$$\n\nTherefore,\n\n$$\n\\operatorname{WCSS}\n=\n\\frac{1}{15}+0.10+0.10\n\\approx\n0.267.\n$$\n\n</details>\n\nSmaller inertia means observations are closer to their assigned centers. However, inertia always decreases as $K$ increases and becomes zero when every distinct observation is its own cluster. Therefore, its absolute minimum cannot be used to choose $K$.\n\n\n\n\n### Silhouette Value\n\nThe <span onclick=\"say('silhouette')\">Silhouette</span> value is another internal evaluation measure. It evaluates both within-cluster cohesion and separation from nearby clusters. For observation $i$, define:\n\n- $a(i)$ as its average distance to other observations in its own cluster;\n- $b(i)$ as the smallest average distance to observations in another cluster.\n\nThe silhouette value is\n\n$$\ns(i)\n=\n\\frac{b(i)-a(i)}\n{\\max\\{a(i),b(i)\\}}.\n$$\n\nIt lies between $-1$ and $1$:\n\n- values near $1$ indicate a well-separated observation;\n- values near $0$ indicate an observation near a cluster boundary;\n- negative values suggest that another cluster may be closer.\n\nThe overall silhouette score is the average of $s(i)$ over all observations. Larger values are preferred. It requires at least two nonempty clusters.\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nfrom sklearn.metrics import silhouette_score\n\nsilhouette_score(X_eval, cluster_eval)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n0.952562475841761\n```\n:::\n:::\n\n\n<details>\n<summary><strong>Click to expand.</strong></summary>\n\nFor example, consider the first observation $x_1=(0.0,0.1)$, which belongs to cluster 0. Its average distance to the other observations in its own cluster is\n\n$$\na(1)\n=\n\\frac{\n\\|(0.0,0.1)-(0.2,0.0)\\|\n+\n\\|(0.0,0.1)-(0.1,0.3)\\|\n}{2}\n\\approx\n0.224.\n$$\n\nNext compute its average distance to each other cluster:\n\n$$\n\\begin{aligned}\nd(1,C_1)\n&=\n\\frac{\n\\|(0.0,0.1)-(4.0,4.1)\\|\n+\\|(0.0,0.1)-(4.2,3.9)\\|\n+\\|(0.0,0.1)-(3.8,4.0)\\|\n}{3}\\\\\n&\\approx 5.589,\n\\end{aligned}\n$$\n\nand\n\n$$\n\\begin{aligned}\nd(1,C_2)\n&=\n\\frac{\n\\|(0.0,0.1)-(8.0,0.0)\\|\n+\\|(0.0,0.1)-(8.2,0.2)\\|\n+\\|(0.0,0.1)-(7.9,-0.1)\\|\n+\\|(0.0,0.1)-(8.1,0.1)\\|\n}{4}\\\\\n&\\approx 8.051.\n\\end{aligned}\n$$\n\nTherefore,\n\n$$\nb(1)=\\min\\{5.589,8.051\\}=5.589,\n$$\n\nand the silhouette value for this observation is\n\n$$\ns(1)\n=\n\\frac{b(1)-a(1)}{\\max\\{a(1),b(1)\\}}\n=\n\\frac{5.589-0.224}{5.589}\n\\approx\n0.960.\n$$\n\nThe Silhouette score for the whole dataset is the mean of the score for each individual observation.\n</details>\n\n\nThis score is close to 1, indicating that most observations are much closer to observations in their assigned cluster than to observations in other clusters.\n\n\n### Stability\n\nA useful clustering should not change drastically under small, reasonable changes to the analysis. Stability asks whether the same broad grouping appears when the data or fitting procedure is slightly perturbed.\n\nCommon checks include rerunning the method with different random seeds, changing tuning parameters slightly, refitting after small changes to preprocessing, or clustering bootstrap or subsampled versions of the data. The numeric cluster labels themselves do not need to match, because labels are arbitrary. What matters is whether similar observations remain grouped together.\n\nStability is not the same as correctness. A clustering can be stable because a method has a strong geometric bias, even if the resulting groups are not scientifically meaningful. It should therefore be considered together with internal scores, visual inspection when possible, and interpretation in the original features.\n\n\n\n### Interpretation in the Original Features\n\nNumerical scores do not explain what a cluster represents. After fitting a clustering, the groups should be described using the original variables. For tabular data, a simple interpretation step is to summarize each feature by cluster.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ncluster_summary = (\n    pd.DataFrame(X_eval, columns=[\"x1\", \"x2\"])\n    .assign(cluster=cluster_eval)\n    .groupby(\"cluster\")\n    .agg([\"mean\", \"std\", \"size\"])\n)\n\ncluster_summary\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead tr th {\n        text-align: left;\n    }\n\n    .dataframe thead tr:last-of-type th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr>\n      <th></th>\n      <th colspan=\"3\" halign=\"left\">x1</th>\n      <th colspan=\"3\" halign=\"left\">x2</th>\n    </tr>\n    <tr>\n      <th></th>\n      <th>mean</th>\n      <th>std</th>\n      <th>size</th>\n      <th>mean</th>\n      <th>std</th>\n      <th>size</th>\n    </tr>\n    <tr>\n      <th>cluster</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.10</td>\n      <td>0.100000</td>\n      <td>3</td>\n      <td>0.133333</td>\n      <td>0.152753</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>4.00</td>\n      <td>0.200000</td>\n      <td>3</td>\n      <td>4.000000</td>\n      <td>0.100000</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>8.05</td>\n      <td>0.129099</td>\n      <td>4</td>\n      <td>0.050000</td>\n      <td>0.129099</td>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-caution}\n## No single score validates a clustering\n\nInternal metrics and Rand-index-based agreement measures answer different questions. A useful clustering should be geometrically coherent, reasonably stable, and interpretable for the problem at hand.\n:::\n\n\n\n\n\n### Optional: Rand Index\n\n\n<details>\n<summary><strong>Click to expand.</strong></summary>\n\n\nWhen reference labels are available, they can be used after clustering for external validation. This setting is common in simulations, benchmark datasets, or applications where external categories are known but intentionally withheld from the clustering algorithm.\n\nExternal validation does not turn clustering into supervised learning because the reference labels are not used during fitting. Instead, it asks how well the cluster assignments agree with an external reference labeling.\n\nThe Rand index compares cluster assignments with reference labels by considering all pairs of observations. A pair is counted as an agreement if the two observations are assigned to the same cluster and have the same reference label, or if they are assigned to different clusters and have different reference labels. The index lies between $0$ and $1$, with larger values indicating stronger agreement.\n\nLet $a$ be the number of observation pairs that are grouped together by both labelings. That is, the two observations have the same cluster assignment and also have the same reference label. Let $b$ be the number of\nobservation pairs that are separated by both labelings. That is, the two observations have different cluster assignments and also have different reference labels. Since there are ${n \\choose 2}$ total pairs, the Rand\nindex is\n\n$$\n\\operatorname{RI}\n=\n\\frac{a+b}{{n \\choose 2}}.\n$$\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\nfrom sklearn.metrics import rand_score\n\nreference_labels = np.array([1, 1, 1, 2, 2, 2, 2, 3, 3, 3])\ncluster_assignments = np.array([0, 0, 0, 1, 1, 2, 2, 2, 2, 2])\n\nrand_score(reference_labels, cluster_assignments)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n0.7777777777777778\n```\n:::\n:::\n\n\nThe diagram below shows where the two labelings agree and disagree. The reference labels define groups $\\{1,2,3\\}$, while the clustering algorithm returns cluster labels $\\{0,1,2\\}$. The mismatch occurs because reference class 2 is split across clusters 1 and 2, and cluster 2 also contains observations from reference class 3.\n\n```{mermaid}\nflowchart LR\n    subgraph Reference labels\n        R1[\"Class 1\"]\n        R2[\"Class 2\"]\n        R3[\"Class 3\"]\n    end\n\n    subgraph Observation groups\n        G1[\"obs 1, 2, 3\"]\n        G2[\"obs 4, 5\"]\n        G3[\"obs 6, 7\"]\n        G4[\"obs 8, 9, 10\"]\n    end\n\n    subgraph Cluster assignments\n        C0[\"Cluster 0\"]\n        C1[\"Cluster 1\"]\n        C2[\"Cluster 2\"]\n    end\n\n    R1 --> G1 --> C0\n    R2 --> G2 --> C1\n    R2 --> G3 --> C2\n    R3 --> G4 --> C2\n```\n\n\n\n\nThe diagram also gives a quick way to compute the four pair counts:\n\n- $a$: pairs together in both labelings. Add ${m\\choose 2}$ within each middle observation group:\n  $a={3\\choose 2}+{2\\choose 2}+{2\\choose 2}+{3\\choose 2}=8$.\n- $c$: pairs together in the reference labels but separated by the cluster\n  assignments. Reference class 2 is split into groups of sizes 2 and 2, so\n  $c=2\\times 2=4$.\n- $d$: pairs separated by the reference labels but together in the cluster\n  assignments. Cluster 2 contains 2 observations from reference class 2 and\n  3 observations from reference class 3, so $d=2\\times 3=6$.\n- $b$: pairs separated by both labelings. The fastest calculation is\n  subtraction from all pairs:\n\n$$\nb\n=\n{10\\choose 2}-a-c-d\n=\n45-8-4-6\n=\n27.\n$$\n\n\n\n\nThere are ${10 \\choose 2}=45$ observation pairs. Among them, $a=8$ pairs are grouped together by both labelings, and $b=27$ pairs are separated by both labelings. Therefore,\n\n$$\n\\operatorname{RI}\n=\n\\frac{8+27}{45}\n\\approx\n0.778.\n$$\n\n\n</details>\n\n\n\n### Optional: Adjusted Rand Index\n\n\n<details>\n<summary><strong>Click to expand.</strong></summary>\n\n\nThe Rand index can be high even when two labelings agree partly by chance, especially when there are many pairs of observations. The adjusted Rand index corrects for this chance agreement.\n\n\n::: {#exm-high-rand-score}\n## A relatively high Rand index can be misleading\n\n\n\nSuppose the reference labels contain two groups of equal size, but the clustering algorithm assigns every observation to its own cluster:\n\n<!-- | Observation | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | -->\n\n| Reference label | 1 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2 | 2 |\n|---|---|---|---|---|---|---|---|---|---|---|\n| Cluster assignment | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |\n\nThis clustering does not recover the two reference groups. However, the Rand index is still above $0.5$ because many pairs from different reference classes are also placed in different clusters. In this example, $a=0$ and $b=25$, so\n\n$$\n\\operatorname{RI}\n=\n\\frac{0+25}{{10\\choose 2}}\n=\n\\frac{25}{45}\n\\approx\n0.556.\n$$\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\nfrom sklearn.metrics import rand_score\n\nreference_labels = [1, 1, 1, 1, 1, 2, 2, 2, 2, 2]\ncluster_assignments = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n\nrand_score(reference_labels, cluster_assignments)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n0.5555555555555556\n```\n:::\n:::\n\n\n:::\n\n\nThe adjusted Rand index compares the observed pairwise agreement with the agreement expected from random labelings with similar group sizes. Suppose $n_{ij}$ is the number of observations that are in reference class $i$ and cluster $j$. Let\n\n$$\na_i=\\sum_j n_{ij},\n\\qquad\nb_j=\\sum_i n_{ij}.\n$$\n\nThus, $a_i$ is the size of reference class $i$, and $b_j$ is the size of cluster $j$. Then the adjusted Rand index is\n\n$$\n\\operatorname{ARI}\n=\n\\frac{\n\\sum_{ij}{n_{ij}\\choose 2}\n-\n\\frac{\n\\sum_i {a_i\\choose 2}\\sum_j {b_j\\choose 2}\n}{{n\\choose 2}}\n}{\n\\frac{1}{2}\n\\left[\n\\sum_i {a_i\\choose 2}\n+\n\\sum_j {b_j\\choose 2}\n\\right]\n-\n\\frac{\n\\sum_i {a_i\\choose 2}\\sum_j {b_j\\choose 2}\n}{{n\\choose 2}}\n}.\n$$\n\n\n\nThe formula has three main parts:\n\n- $\\sum_{ij}{n_{ij}\\choose 2}$ is the observed number of pairs that are placed together in both the reference labels and the cluster assignments.\n- $\\frac{\\sum_i {a_i\\choose 2}\\sum_j {b_j\\choose 2}}{{n\\choose 2}}$ is the expected number of such agreeing pairs under random labelings with the same class sizes and cluster sizes.\n- $\\frac{1}{2}\\left[\\sum_i {a_i\\choose 2}+\\sum_j {b_j\\choose 2}\\right]$ is the average of the largest pair counts implied by the two marginal labelings.\n\nThus, the adjusted Rand index has the form\n\n$$\n\\operatorname{ARI}\n=\n\\frac{\n\\text{observed agreement}\n-\n\\text{expected agreement}\n}{\n\\text{maximum agreement}\n-\n\\text{expected agreement}\n}.\n$$\n\nThe key difference between the Rand index and the adjusted Rand index is that the Rand index measures raw pairwise agreement, while the adjusted Rand index measures pairwise agreement after correcting for chance. This correction matters because many pairs may agree simply because they are separated in both labelings, even when the clustering does not recover the reference groups.\n\n\n\nIts interpretation is:\n\n- $1$ means the two labelings are identical, up to relabeling of the clusters;\n- values near $0$ mean the agreement is about what would be expected by chance;\n- negative values are possible when the agreement is worse than expected by chance.\n\nThis correction is useful because cluster labels themselves are arbitrary. For example, cluster assignments `[0, 0, 1, 1]` and `[2, 2, 5, 5]` describe the same grouping even though the numeric labels are different.\n\n\n\n::: {#exm-}\n## A relatively high Rand index can be misleading (cont.)\n\nContinue from the @exm-high-rand-score.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nfrom sklearn.metrics import adjusted_rand_score\n\nreference_labels = [1, 1, 1, 1, 1, 2, 2, 2, 2, 2]\ncluster_assignments = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n\nadjusted_rand_score(reference_labels, cluster_assignments)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n0.0\n```\n:::\n:::\n\n\nThe adjusted Rand index is $0$, correctly indicating that the observed agreement is no greater than what would be expected by chance.\n:::\n\n\nThe same score can compare two clustering runs on the same observations. This is useful for assessing whether the fitted clustering is stable under small changes in preprocessing, initialization, or resampling.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\ncluster_run_1 = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])\ncluster_run_2 = np.array([1, 1, 1, 0, 0, 0, 2, 2, 2, 2])\n\nadjusted_rand_score(cluster_run_1, cluster_run_2)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n1.0\n```\n:::\n:::\n\n\nThis example gives high agreement even though the numeric cluster labels have changed. That is appropriate because the labels identify groups only up to relabeling.\n\n\n</details>\n\n\n\n## Centroid-Based: K-Means Clustering\n\nK-means represents each cluster by its center. Let $C_1,\\ldots,C_K$ be a partition of the observations, and let\n\n$$\n\\mu_k\n=\n\\frac{1}{|C_k|}\n\\sum_{i\\in C_k}x_i\n$$\n\nbe the center of cluster $k$.\n\n::: {#def-kmeans}\n## K-means objective\n\nK-means chooses the partition that minimizes the within-cluster sum of squares (WCSS):\n\n$$\n\\operatorname{WCSS}\n=\n\\sum_{k=1}^K\n\\sum_{i\\in C_k}\n\\norm{x_i-\\mu_k}_2^2.\n$$\n\nIn `sklearn`, this objective is also called **inertia**.\n:::\n\nThe standard algorithm alternates between two steps:\n\n1. assign each observation to its nearest center;\n2. replace each center by the mean of its assigned observations.\n\nEach step decreases, or leaves unchanged, the K-means objective. The algorithm eventually reaches a local optimum, but not necessarily the global optimum. For this reason, software usually tries several random initializations.\n\n\n### K-means in Python\n\nWe use a simulated dataset to illustrate K-means in Python.\n\nWe use `make_blobs` from `sklearn.datasets` to generate 500 observations from three latent groups. The data have two features so that the result can be visualized directly. The colors below show the generating labels. They are not used when fitting K-means.\n\n<!-- fmt: off -->\n\n::: {.cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nfrom sklearn.datasets import make_blobs\nimport matplotlib.pyplot as plt\n\nX, true_group = make_blobs(\n    n_samples=500,\n    n_features=2,\n    centers=3,\n    cluster_std=[0.7, 0.9, 0.8],\n    random_state=3,\n)\n\nplt.scatter(X[:, 0], X[:, 1], c=true_group)\nplt.xlabel(\"x1\")\nplt.ylabel(\"x2\")\nplt.title(\"Simulated Groups\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-10-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n<!-- fmt: on -->\n\n`KMeans` follows the usual `sklearn` interface. Since clustering is performed on the observed data themselves, we fit the model to the feature matrix and obtain cluster assignments for the observations.\n\nFor this first illustration, we set `n_clusters=3` so that the fitted result can be compared visually with the simulated groups. This does not represent how $K$ is chosen in practice. In real applications, the number of clusters is usually unknown and must be treated as a tuning choice.\n\nAs mentioned previously, it is recommended to use multiple random initializations to reduce sensitivity to a poor starting configuration. The argument `n_init=20` runs K-means from 20 different initial center configurations and retains the solution with the smallest inertia among those runs.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nfrom sklearn.cluster import KMeans\n\nkmeans = KMeans(n_clusters=3, n_init=20, random_state=1)\nkmeans.fit(X)\ncluster = kmeans.predict(X) # <1>\n```\n:::\n\n\n1. You may also use `cluster = kmeans.fit_predict(X)` to combine the two commands together.\n\n`cluster` is an array of cluster assignments, one for each observation. We can then plot the observations with colors indicating their assigned clusters.\n<!-- fmt: off -->\n\n::: {.cell execution_count=11}\n``` {.python .cell-code code-fold=\"true\"}\nplt.scatter(X[:, 0], X[:, 1], c=cluster)\nplt.scatter(\n    kmeans.cluster_centers_[:, 0],\n    kmeans.cluster_centers_[:, 1],\n    marker=\"X\",\n    color=\"black\",\n    label=\"centers\",\n)\nplt.xlabel(\"x1\")\nplt.ylabel(\"x2\")\nplt.title(\"K-Means Clustering\")\nplt.legend();\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-12-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n<!-- fmt: on -->\n\nThe fitted centers are available from the model.\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nkmeans.cluster_centers_\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\narray([[ 1.01494239,  4.19111967],\n       [ 7.70936555,  8.07424709],\n       [-4.1867326 ,  0.2695436 ]])\n```\n:::\n:::\n\n\n::: {.callout-note}\n## Label switching\n\nCluster labels are arbitrary. A cluster labeled `0` in one fit may be labeled `2` in another fit even when the two clusterings are equivalent. Interpret the groups through their members and feature summaries, not the numeric label.\n:::\n\n\n### Tuning Hyperparameters\n\nThe most important K-means hyperparameter is `n_clusters`, the number of centers to fit. A larger value gives a more detailed clustering and lowers the within-cluster sum of squares, but it may split groups that are better interpreted together. A smaller value gives a coarser summary but may merge distinct groups. There is no universally correct criterion because the useful level of grouping depends on the scientific question.\n\nTwo common diagnostics for choosing `n_clusters` are inertia and the silhouette score. The elbow plot examines inertia over a range that includes $K=1$. The silhouette score compares within-cluster cohesion with separation from neighboring clusters and is computed only for $K\\ge 2$.\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\nfrom sklearn.metrics import silhouette_score\n\ninertia_k = range(1, 11)\ninertias = []\nfor k in inertia_k:\n    model = KMeans(n_clusters=k, n_init=20, random_state=1)\n    model.fit(X)\n    inertias.append(model.inertia_)\n\nsilhouette_k = range(2, 11)\nsilhouettes = []\nfor k in silhouette_k:\n    model = KMeans(n_clusters=k, n_init=20, random_state=1)\n    labels = model.fit_predict(X)\n    silhouettes.append(silhouette_score(X, labels))\n```\n:::\n\n\nPlot the two diagnostics together.\n\n::: {.cell execution_count=14}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib.pyplot as plt\n\nfig, axs = plt.subplots(1, 2, figsize=(11, 4))\n\naxs[0].plot(inertia_k, inertias, marker=\"o\")\naxs[0].set_xlabel(\"number of clusters K\")\naxs[0].set_ylabel(\"inertia\")\naxs[0].set_title(\"Elbow Plot\")\n\naxs[1].plot(silhouette_k, silhouettes, marker=\"o\")\naxs[1].set_xlabel(\"number of clusters K\")\naxs[1].set_ylabel(\"average silhouette\")\naxs[1].set_title(\"Silhouette Score\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-15-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nFor inertia, the elbow heuristic looks for the point after which additional clusters produce only modest improvement. In this example, the largest improvements occur for small values of $K$, and $K=3$ is a plausible elbow.\n\nFor the silhouette score, larger values are preferred. In this example, the average silhouette score is largest at $K=3$ over the range considered.\n\nThe two diagnostics can disagree because they measure different aspects of the cluster assignments. The final choice of $K$ should be guided by the analysis goal, stability, and interpretability, not by a single plot alone. In this simulated example, the diagnostics are consistent with the illustrative choice $K=3$.\n\n\nOther K-means hyperparameters control how the optimization is carried out:\n\n- `init` controls how the initial centers are chosen. The default `\"k-means++\"` spreads initial centers out and is usually preferable to purely random initialization.\n- `n_init` controls how many initial center configurations are tried. Since K-means can stop at a local optimum, using several starts makes the result less dependent on one unlucky initialization.\n- `max_iter` is the maximum number of assignment-update steps for one initialization.\n- `tol` controls the convergence tolerance. Smaller values ask the algorithm to keep iterating until the centers change very little.\n- `random_state` makes randomized initialization reproducible.\n\nFor routine analyses, it is common to use `init=\"k-means++\"` (which is the default value in the current version of `sklearn`) and tune `n_clusters`, while using a reasonably large `n_init`.\n\n::: {.callout-caution}\n## Diagnostics do not define the scientific answer\n\nWCSS and the silhouette score evaluate geometric compactness and separation under the chosen features, scaling, and distance. They do not show that the clusters are stable, scientifically meaningful, or useful for a later decision.\n:::\n\n\n### When K-Means Works Well\n\nBecause K-means uses squared Euclidean distance to a center, it is most effective when clusters are:\n\n- compact and approximately spherical;\n- separated by their centers;\n- reasonably similar in size and spread;\n- not dominated by extreme outliers.\n\nIt can perform poorly on curved clusters, clusters with very different densities, or data where a mean is not an appropriate prototype.\n\n::: {.cell execution_count=15}\n``` {.python .cell-code code-fold=\"true\"}\nfrom sklearn.datasets import make_circles\nfrom sklearn.cluster import KMeans\nimport matplotlib.pyplot as plt\n\nX_circle, true_circle_group = make_circles(\n    n_samples=500, factor=0.45, noise=0.05, random_state=1\n)\n\ncircle_kmeans = KMeans(n_clusters=2, n_init=20, random_state=1)\ncircle_cluster = circle_kmeans.fit_predict(X_circle)\n\nfig, axs = plt.subplots(1, 2, figsize=(10, 4), sharex=True, sharey=True)\n\naxs[0].scatter(X_circle[:, 0], X_circle[:, 1], c=true_circle_group)\naxs[0].set_title(\"Underlying Structure\")\n\naxs[1].scatter(X_circle[:, 0], X_circle[:, 1], c=circle_cluster)\naxs[1].set_title(\"K-Means Partition\")\n\nfor ax in axs:\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-16-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nK-means divides the feature space into convex regions, so it cannot recover the two rings. \n\n## Hierarchical: Agglomerative Clustering\n\n<span onclick=\"say('hierarchical')\">Hierarchical</span> clustering builds a nested sequence of clusterings. <span onclick=\"say('agglomerative')\">Agglomerative</span> hierarchical clustering begins with each observation in its own cluster and repeatedly merges the two \"closest\" clusters until all observations belong to one cluster.\n\nThe result is a tree called a <span onclick=\"say('dendrogram')\">**dendrogram**</span>. Unlike K-means, the hierarchy can be fit before choosing the final number of clusters.\n\n\n### Linkage\n\nAt each step of agglomerative hierarchical clustering, we merge the two closest clusters. To determine which clusters are closest, we first need to define the distance between clusters. A linkage rule specifies how this distance is computed.\n\nFor two clusters $G$ and $H$, common linkage rules include:\n\n- Single linkage uses the closest pair: $d_{\\text{single}}(G,H)=\\min_{i\\in G,\\;j\\in H}d(x_i,x_j).$\n- Complete linkage uses the farthest pair: $d_{\\text{complete}}(G,H)=\\max_{i\\in G,\\;j\\in H}d(x_i,x_j).$\n- Average linkage uses the average pairwise distance: $d_{\\text{avg}}(G,H)=\\frac{1}{|G||H|}\\sum_{i\\in G,j\\in H}d(x_i,x_j).$\n- Ward linkage merges the pair of clusters that produces the smallest increase in the within-cluster sum of squares (WCSS). Unlike the previous linkage rules, Ward linkage is based on cluster variance rather than pairwise distances, and therefore tends to produce compact, approximately spherical clusters.\n\nDifferent linkage rules represent different notions of what makes two clusters close. Single linkage can recover elongated or irregularly shaped clusters, but it is sensitive to the chaining effect, where intermediate points connect otherwise separate groups. Complete linkage and Ward linkage are less affected by chaining and tend to produce more compact clusters.\n\n\n### Dendrogram\n\nA dendrogram is a visual record of the sequence of merges. At the beginning, each observation is its own cluster. At each step, the two closest current clusters are merged according to the chosen linkage rule. The height of the merge records the dissimilarity at which the two branches are joined.\n\nThe merge height is not always the distance between two individual observations. It is the dissimilarity between the two clusters being merged, as defined by the linkage rule. For single linkage, the height is the smallest pairwise distance between the two clusters. For complete linkage, it is the largest pairwise distance; for average linkage, it is the average pairwise distance; and for Ward linkage, it is based on the increase in within-cluster variation caused by the merge.\n\nFor example, consider five one-dimensional observations:\n\n$$\n0.0,\\quad 0.2,\\quad 0.3,\\quad 3.0,\\quad 3.2.\n$$\n\nUsing single linkage, the tree is built as follows:\n\n1. Merge $0.2$ and $0.3$, the closest pair, at height $0.1$.\n2. Merge $0.0$ with the cluster $\\{0.2,0.3\\}$ at height $0.2$.\n3. Merge $3.0$ and $3.2$ at height $0.2$.\n4. Merge the two larger clusters $\\{0.0,0.2,0.3\\}$ and $\\{3.0,3.2\\}$ at height $2.7$.\n\n::: {.cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-17-output-1.pdf){}\n:::\n:::\n\n\nThe toy dendrogram shows the main interpretation: observations that merge at low heights are similar under the chosen linkage rule, while branches that merge only at high heights are more separated.\n\n### Hierarchical clustering in Python\n\nIn `sklearn`, agglomerative hierarchical clustering is fit using `AgglomerativeClustering`. Here we apply it to the simulated dataset from K-means. Like other `sklearn` estimators, it provides `fit_predict` for returning cluster assignments.\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\nfrom sklearn.cluster import AgglomerativeClustering\nhierarchical_model = AgglomerativeClustering(n_clusters=3, linkage=\"single\")\nhierarchical_cluster = hierarchical_model.fit_predict(X)\n```\n:::\n\n\nHere `n_clusters=3` is chosen for illustration. We can visualize the resulting cluster assignments in the original feature space.\n\n::: {.cell execution_count=18}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nplt.scatter(X[:, 0], X[:, 1], c=hierarchical_cluster)\nplt.xlabel(\"x1\")\nplt.ylabel(\"x2\")\nplt.title(\"Hierarchical Clustering Assignments\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-19-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n`sklearn` can fit an agglomerative hierarchical clustering model and return the cluster assignments, but it does not provide a function to directly plot a dendrogram. For visualization, we use `linkage` from `scipy.cluster.hierarchy` to compute the hierarchy and `dendrogram` to display the resulting merge tree.\n\n::: {.cell execution_count=19}\n``` {.python .cell-code}\nfrom scipy.cluster.hierarchy import linkage, dendrogram\n\nZ = linkage(X, method=\"single\")\ndendrogram(Z)\nplt.xlabel(\"observation\")\nplt.ylabel(\"merge height\")\nplt.title(\"Hierarchical Clustering Dendrogram\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-20-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe merge height records the dissimilarity at which two clusters are merged. The dendrogram summarizes the fitted hierarchy, not uncertainty about the hierarchy.\n\n\n::: {.callout-note}\n## Cutting the Dendrogram\n\nHierarchical clustering separates fitting the hierarchy from choosing the final flat clustering. One conceptual approach is to inspect the dendrogram and make a horizontal cut at a merge height. This keeps merges below the cut and separates branches that would only merge above the cut.\n\nThe cut height is often chosen by looking for a large vertical gap in the dendrogram, but this is only a heuristic. It should be checked against the analysis goal, stability, validation scores, and interpretability.\n:::\n\n\n::: {.callout-note}\n## `n_clusters` versus a height cut\n\nIn `sklearn`, the usual `AgglomerativeClustering(n_clusters=...)` interface asks for an exact number of clusters. This is not the same as drawing a horizontal line at a fixed dendrogram height. The algorithm can return any requested value of `n_clusters`, even when several merges occur at the same height. Operationally, this is equivalent to following the merge sequence determined by the implementation and stopping when exactly `n_clusters` groups remain, rather than choosing all merges below a fixed height. If several candidate merges have the same height, the order is implementation-determined, not random.\n\nIf the goal is a strict height-based cut, use `scipy.cluster.hierarchy.linkage` with `fcluster`, or use `AgglomerativeClustering` with `distance_threshold` and `n_clusters=None`. In this chapter, we focus mainly on the `sklearn` `n_clusters` interface because it is simple and matches the way the examples compare flat cluster assignments.\n:::\n\n\n### Comparing Linkages\n\nTo make the effect of linkage visible, we use a dataset whose geometry is not compact or spherical. The two-moons data have two curved groups, so different linkage rules can produce noticeably different flat clusterings.\n\nAlthough the data are generated from two underlying groups, we set `n_clusters=4` here to make the behavior of the linkage rules easier to compare.\n\n::: {.cell execution_count=20}\n``` {.python .cell-code code-fold=\"true\"}\nfrom sklearn.cluster import AgglomerativeClustering\nfrom sklearn.datasets import make_moons\nimport matplotlib.pyplot as plt\n\nX_ex, _ = make_moons(n_samples=400, noise=0.06, random_state=6)\n\nmethods = [\"single\", \"complete\", \"average\", \"ward\"]\nfig, axs = plt.subplots(2, 2, figsize=(10, 8), sharex=True, sharey=True)\n\nfor ax, method in zip(axs.ravel(), methods):\n    model = AgglomerativeClustering(n_clusters=4, linkage=method)\n    labels = model.fit_predict(X_ex)\n\n    ax.scatter(X_ex[:, 0], X_ex[:, 1], c=labels)\n    ax.set_title(method)\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-21-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe cluster labels are arbitrary, so the important feature is the shape of the split:\n\n- Single linkage uses the closest pair of observations between two clusters. It favors connected shapes and can follow long curves. In the plot, it keeps most of each moon as a connected chain, and the extra clusters appear where a small gap breaks the chain.\n- Complete linkage uses the farthest pair of observations between two clusters. It favors clusters with small diameter, so it tends to produce compact, ball-like groups rather than long or stretched groups. In the plot, it cuts the moons into shorter pieces instead of preserving the full curved shapes.\n- Average linkage uses the average distance over all pairs of observations between two clusters. It is a compromise between connectivity and compactness: it is less sensitive to one nearby pair than single linkage, but less strict about the farthest pair than complete linkage. In the plot, it still splits the moons where the average distance to the rest of the arc becomes large.\n- Ward linkage merges clusters that cause the smallest increase in WCSS. It favors compact, variance-minimizing clusters, similar in spirit to K-means. In the plot, its cuts look like local spatial blocks rather than moon-shaped pieces, because the curved groups are not compact around a single center.\n\n::: {.callout-note}\n## Complete linkage and Ward linkage\n\nComplete linkage and Ward linkage both tend to produce compact, ball-like clusters, but they measure compactness differently.\n\n- Complete linkage is based on cluster diameter. It avoids merges that would make the farthest two observations in a cluster too far apart.\n- Ward linkage is based on within-cluster variation. It avoids merges that would cause a large increase in WCSS, where each cluster is summarized by its mean.\n\nThus, complete linkage is diameter-based compactness, while Ward linkage is variance-based compactness.\n\nThey can differ when cluster sizes or shapes are uneven. Complete linkage reacts strongly to the most distant pair of observations, so one outlying point can prevent a merge by making the cluster diameter too large. Ward linkage reacts to the overall increase in WCSS, so it also depends on cluster sizes and centroids. If two large clusters have nearby centers, Ward linkage may still merge them even when a few observations are relatively far apart, because those observations may not dominate the total WCSS increase.\n:::\n\n\n### When Hierarchical Clustering Works Well\n\nHierarchical clustering is especially useful when the nested structure itself is meaningful. For example, it is often used to organize genes, documents, products, or other observations where relationships at multiple levels of granularity are informative.\n\nIt is most useful when:\n\n- the hierarchy itself is part of the interpretation;\n- one wants to inspect several possible numbers of clusters from the same fitted tree;\n- the dataset is small or moderate in size;\n- the chosen linkage rule matches the geometry of the groups.\n\nHowever, agglomerative clustering can be computationally expensive for very large datasets, and early merges cannot be undone. A suboptimal early merge can affect the rest of the tree.\n\n\n## Density-Based: DBSCAN\n\nDensity-based spatial clustering of applications with noise (DBSCAN) defines clusters as connected regions of sufficiently high local density. Unlike K-means or hierarchical clustering, DBSCAN does not require the number of clusters to be specified in advance.\n\nThe main idea is that a cluster should be a dense region separated from other dense regions by lower-density space. This makes DBSCAN useful when clusters are curved, irregularly shaped, or when some observations should be treated as noise rather than forced into a cluster.\n\nDBSCAN uses two main parameters:\n\n- `eps`: the radius of a local neighborhood;\n- `min_samples`: the number of observations required for a dense neighborhood, including the observation itself.\n\nThese parameters define three types of observations:\n\n- A **core point** has at least `min_samples` observations in its `eps` neighborhood, including itself.\n- A **border point** is not a core point, but lies within the `eps` neighborhood of a core point.\n- A **noise point** is neither a core point nor a border point.\n\n### How DBSCAN Forms Clusters\n\nDBSCAN begins by checking the `eps` neighborhood of each observation. If an observation has at least `min_samples` observations in that neighborhood, counting itself, it becomes a core point. A core point can start a new cluster if it has not already been reached from another core point.\n\nOnce a core point starts a cluster, DBSCAN adds all observations within its `eps` neighborhood. If any of those observations are also core points, their own `eps` neighborhoods are added as well. This expansion continues until no new core points can be reached. All core points connected in this way belong to the same cluster, and non-core points reached from those core points are included as border points.\n\nObservations that are not reachable from any core point are labeled as noise. Thus, DBSCAN does not assign points by nearest center. It forms clusters by following chains of dense neighborhoods, and the number of clusters is whatever number of separated dense regions the algorithm finds.\n\n### DBSCAN in Python\nWe use `DBSCAN` from `sklearn.cluster` to implement the method. \n\n::: {.cell execution_count=21}\n``` {.python .cell-code}\nfrom sklearn.cluster import DBSCAN\nfrom sklearn.datasets import make_circles\n\n\nX_circle, true_circle_group = make_circles(\n    n_samples=500, factor=0.45, noise=0.05, random_state=1\n)\n\ncircle_dbscan = DBSCAN(eps=0.13, min_samples=4)\ncircle_dbscan_group = circle_dbscan.fit_predict(X_circle)\n```\n:::\n\n\n::: {.cell execution_count=22}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib.pyplot as plt\n\nfig, axs = plt.subplots(1, 2, figsize=(10, 4), sharex=True, sharey=True)\n\naxs[0].scatter(X_circle[:, 0], X_circle[:, 1], c=circle_cluster)\naxs[0].set_title(\"K-Means\")\n\naxs[1].scatter(X_circle[:, 0], X_circle[:, 1], c=circle_dbscan_group)\naxs[1].set_title(\"DBSCAN\")\n\nfor ax in axs:\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-23-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nIn `sklearn`, noise observations receive the label `-1`. As with all\nclustering labels, the nonnegative cluster labels have no ordinal meaning.\n\n### Choosing `eps` and `min_samples`\n\nThe most important DBSCAN hyperparameter is `eps`, because it controls the scale at which density is measured. A smaller `eps` makes neighborhoods smaller and the density requirement stricter. This may split clusters or label more observations as noise. A larger `eps` makes neighborhoods larger and can merge groups through low-density bridges.\n\nThe parameter `min_samples` controls how much local support is required for a point to be considered a core point. Larger values make the method more conservative and usually produce more noise points.\n\n\n\nA practical workflow is to first set `min_samples`, then use the data to select `eps`. A common starting choice is to set `min_samples` to about twice the number of features. In this two-dimensional example, we use `4`.\n\n\n::: {.callout-note}\n## Checking `min_samples`\n\nThere is no supervised-style cross-validation rule for choosing `min_samples`. A reasonable value should give a stable and interpretable density structure: nearby choices should not radically change the main clusters, and the fraction of noise points should be plausible for the problem. A lower noise fraction is not automatically better, because forcing sparse points into clusters may hide outliers or connect groups through weak bridges.\n\nSeveral diagnostics can help. For a chosen `min_samples`, the k-distance plot should ideally show a reasonably clear elbow, suggesting a defensible density scale. As a starting point, two-dimensional data often use `min_samples=4` or\n`5`; more generally, one may start around `p + 1` or `2p`, where $p$ is the number of features.\n\nIf external labels are available, the Rand index or adjusted Rand index can be used as additional diagnostics.\n:::\n\n\nAfter choosing `min_samples`, compute the distance from each observation to the neighbor that determines whether it is a core point. Since `min_samples` includes the observation itself in `sklearn`, this is the distance to the `min_samples`-th nearest observation when the observation itself is included as the first neighbor. Points inside dense regions should have small such distances, while isolated or low-density points should have larger distances. Sorting these distances gives a diagnostic plot. A visible elbow in the plot suggests a candidate value of `eps`.\n\nIn Python we can use `NearestNeighbors` from `sklearn.neighbors` to compute these distances. The result is then sorted and plotted.\n\n::: {.cell execution_count=23}\n``` {.python .cell-code}\nfrom sklearn.neighbors import NearestNeighbors\n\nmin_samples = 4\n\nneighbors = NearestNeighbors(n_neighbors=min_samples)\nneighbors.fit(X_circle)\n\ndistances, indices = neighbors.kneighbors(X_circle)\nk_distances = np.sort(distances[:, -1])\n\nplt.plot(k_distances)\nplt.axhline(y=0.13, ls=\"--\")\nplt.xlabel(\"sorted observation index\")\nplt.ylabel(f\"distance to {min_samples}-th nearest neighbor\")\nplt.title(\"K-Distance Plot for Choosing eps\");\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-24-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nA candidate `eps` can be drawn as a horizontal line on this plot. Observations with k-distances below the line satisfy the core-point density requirement. Observations above the line are not core points; they may later become border points if they lie within `eps` of a core point, or they may be labeled as noise.\n\nThus, decreasing `eps` usually creates fewer core points, more noise, and a greater chance that a dense region is split into pieces. Increasing `eps` usually creates more core points and a greater chance that nearby dense regions are merged through a bridge of points.\n\nIn this example, the curve remains relatively flat for most observations and then increases more sharply for observations whose local neighborhoods are sparser. An `eps` value near the bend separates the dense ring structure from the lower-density gaps. We next check nearby values.\n\n::: {.cell execution_count=24}\n``` {.python .cell-code code-fold=\"true\"}\neps_values = [0.12, 0.13, 0.14]\n\nfig, axs = plt.subplots(1, 3, figsize=(12, 4), sharex=True, sharey=True)\n\nfor ax, eps in zip(axs, eps_values):\n    labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(X_circle)\n\n    ax.scatter(X_circle[:, 0], X_circle[:, 1], c=labels)\n    ax.set_title(f\"eps = {eps}\")\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-25-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nIf small changes in `eps` lead to very different cluster assignments, the density structure may not be stable at a single scale. In that case, the fitted clusters should be interpreted cautiously, or a method designed for varying density levels may be more appropriate.\n\nIn this example, from `0.12` to `0.14` the clustering structure is relatively stable. The color labels may change because cluster labels are arbitrary, but the two-ring grouping is essentially the same. Therefore, `0.13` is a reasonable choice within this stable range.\n\n::: {.callout-caution}\n## Silhouette scores are only a rough diagnostic for DBSCAN\n\nOne can compute silhouette scores over a grid of `eps` and `min_samples` values, but this is not ordinary cross-validation because clustering has no supervised prediction error. The score is also harder to interpret for DBSCAN: treating noise as an extra cluster can distort the score, while removing noise ignores one of DBSCAN's main outputs.\n\nSilhouette scores also favor compact, well-separated groups, whereas DBSCAN is often used for curved or irregular clusters. Use them only as a secondary diagnostic alongside the k-distance plot, the number of clusters, the fraction of noise points, visual inspection when possible, and sensitivity to nearby parameter values.\n:::\n\n::: {.callout-note}\n## DBSCAN does not tune `n_clusters`\n\nDBSCAN determines the number of clusters from the density structure induced by `eps` and `min_samples`. This is useful when the number of groups is unknown, but it also means that the result can change substantially when the density scale changes.\n:::\n\n### When DBSCAN Works Well\n\nDBSCAN is most useful when:\n\n- clusters have irregular or curved shapes;\n- clusters are separated by sparse regions;\n- noise points should be explicitly identified;\n- a single density scale is reasonable for the dataset.\n\nIt is less effective when cluster densities differ substantially. One global value of `eps` may be too small for a sparse cluster and too large for a dense cluster.\n\n\n## Comparing the Three Methods\n\nThe three direct methods answer different versions of the clustering question. The key difference is their definitions of a cluster: what each method treats as evidence that observations belong together:\n\n| Method | Informal rule | Works especially well when |\n|---|---|---|\n| K-means | Points belong together if they are close to the same center. | clusters are roughly spherical, compact, and similar in size |\n| Hierarchical clustering | Points belong together if they are joined through a sequence of merges. | one wants to explore grouping structure at several resolutions |\n| DBSCAN | Points belong together if they lie in the same sufficiently dense region. | clusters are dense regions, noise is present, and the number of clusters is unknown |\n\nNo method is uniformly best. The geometry of the data, the intended definition of a cluster, and the scientific question should determine which paradigm is appropriate. A useful comparison does not require every method to look successful; a poor-looking fit can be informative when it reveals the method's assumptions.\n\n\n\n- K-means is fast, simple, and often the practical default when $K$ is known and clusters are roughly compact and center-based. It can revise assignments during iteration, but it forces every observation into one of the $K$ clusters and is not designed for curved shapes or explicit noise.\n- Agglomerative hierarchical clustering is most useful when the merge sequence or dendrogram is part of the interpretation. It can show several possible resolutions from one fitted tree, but early merges cannot be undone and classical agglomerative methods scale poorly because they rely on many pairwise dissimilarities.\n- DBSCAN is useful when clusters are dense regions separated by sparse space. It does not require `n_clusters` and can label observations as noise, but it is sensitive to the density scale set by `eps` and `min_samples` and does not show nested structure.\n\nWe show three examples below illustrating the strengths and limitations of each method. These examples are not a ranking. They show that each method is answering a different question: nearest center, merge tree, or density connectivity. In the examples, the hierarchical clustering result uses single linkage. When a method performs poorly on a particular geometry, the failure is still useful if it matches the method's definition of a cluster.\n\nSince all datasets are generated, we know the true label for each observation. Therefore, we can use ARI as an external metric to compare the clustering results on each dataset. ARI is optional and was introduced earlier in the notes.\n\nIn the curves-with-noise example, the artificially added noise points are treated as a separate reference group when computing ARI. This is a teaching device for simulated data, not something usually available in real applications. It favors methods that can identify noise points, such as DBSCAN, and penalizes methods such as K-means and hierarchical clustering that must assign every observation to a cluster.\n\n### Example: Curves with Noise\n\n<!-- fmt: off -->\n\n::: {.cell execution_count=25}\n``` {.python .cell-code code-fold=\"true\"}\nfrom sklearn.datasets import make_blobs, make_moons\nfrom sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN\nfrom sklearn.metrics import adjusted_rand_score\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nrng = np.random.default_rng(2)\n\nX_moon, true_moon_group = make_moons(n_samples=450, noise=0.06, random_state=2)\nmoon_noise = rng.uniform(low=[-1.5, -0.8], high=[2.5, 1.3], size=(30, 2))\nX_moon_noise = np.vstack([X_moon, moon_noise])\ntrue_moon_noise_group = np.concatenate(\n    [true_moon_group, np.repeat(-1, len(moon_noise))]\n)\n\nkmeans_labels = KMeans(n_clusters=2, n_init=20, random_state=1).fit_predict(\n    X_moon_noise\n)\n\nsingle_labels = AgglomerativeClustering(n_clusters=2, linkage=\"single\").fit_predict(\n    X_moon_noise\n)\n\ndbscan_labels = DBSCAN(eps=0.16, min_samples=6).fit_predict(X_moon_noise)\n\nkmeans_ari = adjusted_rand_score(true_moon_noise_group, kmeans_labels)\nsingle_ari = adjusted_rand_score(true_moon_noise_group, single_labels)\ndbscan_ari = adjusted_rand_score(true_moon_noise_group, dbscan_labels)\n\nfig, axs = plt.subplots(1, 3, figsize=(12, 3.5), sharex=False, sharey=False)\n\naxs[0].scatter(X_moon_noise[:, 0], X_moon_noise[:, 1], c=kmeans_labels, s=16)\naxs[0].set_title(f\"K-Means\\nARI = {kmeans_ari:.2f}\")\n\naxs[1].scatter(X_moon_noise[:, 0], X_moon_noise[:, 1], c=single_labels, s=16)\naxs[1].set_title(f\"Hierarchical: Single\\nARI = {single_ari:.2f}\")\n\naxs[2].scatter(X_moon_noise[:, 0], X_moon_noise[:, 1], c=dbscan_labels, s=16)\naxs[2].set_title(f\"DBSCAN\\nARI = {dbscan_ari:.2f}\")\n\nfor ax in axs:\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n\nfig.suptitle(\"Curves with Noise\", y=1.05);\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-26-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe moon dataset contains two curved dense regions plus scattered noise. \n\n- DBSCAN works best here because it defines clusters as dense connected regions, so it can follow the two curved shapes and leave scattered observations as noise.\n- K-means has trouble because each cluster is represented by a center, which breaks the curved geometry into center-based regions. \n- Hierarchical clustering using single linkage can follow connected shapes, but scattered noise may create unwanted connections or unbalanced cuts.\n\n### Example: Unequal Densities\n\n::: {.cell execution_count=26}\n``` {.python .cell-code code-fold=\"true\"}\nX_unequal_density, true_unequal_density_group = make_blobs(\n    n_samples=[180, 220, 260],\n    centers=[[-4.0, 0], [0.0, 0], [4.5, 0]],\n    cluster_std=[0.18, 0.55, 1.15],\n    random_state=8,\n)\n\nkmeans_labels = KMeans(n_clusters=3, n_init=20, random_state=1).fit_predict(\n    X_unequal_density\n)\n\nsingle_labels = AgglomerativeClustering(n_clusters=3, linkage=\"single\").fit_predict(\n    X_unequal_density\n)\n\ndbscan_labels = DBSCAN(eps=0.40, min_samples=6).fit_predict(X_unequal_density)\n\nkmeans_ari = adjusted_rand_score(true_unequal_density_group, kmeans_labels)\nsingle_ari = adjusted_rand_score(true_unequal_density_group, single_labels)\ndbscan_ari = adjusted_rand_score(true_unequal_density_group, dbscan_labels)\n\nfig, axs = plt.subplots(1, 3, figsize=(12, 3.5), sharex=False, sharey=False)\n\naxs[0].scatter(X_unequal_density[:, 0], X_unequal_density[:, 1], c=kmeans_labels, s=16)\naxs[0].set_title(f\"K-Means\\nARI = {kmeans_ari:.2f}\")\n\naxs[1].scatter(X_unequal_density[:, 0], X_unequal_density[:, 1], c=single_labels, s=16)\naxs[1].set_title(f\"Hierarchical: Single\\nARI = {single_ari:.2f}\")\n\naxs[2].scatter(X_unequal_density[:, 0], X_unequal_density[:, 1], c=dbscan_labels, s=16)\naxs[2].set_title(f\"DBSCAN\\nARI = {dbscan_ari:.2f}\")\n\nfor ax in axs:\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n\nfig.suptitle(\"Unequal Densities\", y=1.05);\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-27-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe unequal-density dataset illustrates a limitation of DBSCAN. The three groups have very different spreads. \n\n- K-means is relatively effective here because the groups are still roughly center-based, even though their densities differ.\n- DBSCAN is less effective here than K-means and is more sensitive to the chosen `eps`, because one global `eps` may be appropriate for the dense group but too small for the sparse group, or appropriate for the sparse group but too large for the dense group. \n- Hierarchical clustering using single linkage can also be unstable here because a few close points between groups can create early connections that affect the later merges.\n\n### Example: Uneven Chains\n\n::: {.cell execution_count=27}\n``` {.python .cell-code code-fold=\"true\"}\nrng_chain = np.random.default_rng(9)\nt_chain = np.concatenate([np.linspace(0, 1.1, 170), np.linspace(1.1, np.pi, 35)])\nupper_chain = np.column_stack([np.cos(t_chain), np.sin(t_chain)])\nlower_chain = np.column_stack([1 - np.cos(t_chain), 0.5 - np.sin(t_chain)])\nX_chain = np.vstack([upper_chain, lower_chain]) + rng_chain.normal(\n    scale=0.025, size=(2 * len(t_chain), 2)\n)\ntrue_chain_group = np.concatenate(\n    [np.repeat(0, len(t_chain)), np.repeat(1, len(t_chain))]\n)\n\nkmeans_labels = KMeans(n_clusters=2, n_init=20, random_state=1).fit_predict(X_chain)\n\nsingle_labels = AgglomerativeClustering(n_clusters=2, linkage=\"single\").fit_predict(\n    X_chain\n)\ndbscan_labels = DBSCAN(eps=0.08, min_samples=6).fit_predict(X_chain)\n\nkmeans_ari = adjusted_rand_score(true_chain_group, kmeans_labels)\nsingle_ari = adjusted_rand_score(true_chain_group, single_labels)\ndbscan_ari = adjusted_rand_score(true_chain_group, dbscan_labels)\n\nfig, axs = plt.subplots(1, 3, figsize=(12, 3.5), sharex=False, sharey=False)\n\naxs[0].scatter(X_chain[:, 0], X_chain[:, 1], c=kmeans_labels, s=16)\naxs[0].set_title(f\"K-Means\\nARI = {kmeans_ari:.2f}\")\n\naxs[1].scatter(X_chain[:, 0], X_chain[:, 1], c=single_labels, s=16)\naxs[1].set_title(f\"Hierarchical: Single\\nARI = {single_ari:.2f}\")\n\naxs[2].scatter(X_chain[:, 0], X_chain[:, 1], c=dbscan_labels, s=16)\naxs[2].set_title(f\"DBSCAN\\nARI = {dbscan_ari:.2f}\")\n\nfor ax in axs:\n    ax.set_xlabel(\"x1\")\n    ax.set_ylabel(\"x2\")\n\nfig.suptitle(\"Uneven Chains\", y=1.05);\n```\n\n::: {.cell-output .cell-output-display}\n![](cluster_files/figure-pdf/cell-28-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n<!-- fmt: on -->\n\nThe uneven-chain dataset illustrates a case where hierarchical clustering using single linkage can be useful. The groups are best described as connected chains with uneven spacing. \n\n- Single linkage can follow each chain through nearest-neighbor connections, so it is the most natural fit among the three methods. \n- K-means instead cuts the plane into center-based regions, which mixes parts of the two chains. \n- DBSCAN can label the thinner parts on both sides of the chains as noise when one global density scale is used. In this example, those side segments are not merged into one cluster; they are mostly excluded as noise because they are too sparse under the chosen `eps` and `min_samples`.\n\n",
    "supporting": [
      "cluster_files\\figure-pdf"
    ],
    "filters": []
  }
}